/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import * as zod from 'zod';

/**
 * Universal token endpoint supporting client_credentials, authorization_code, and refresh_token grant types. RFC 6749 compliant with form-encoded requests and JSON responses. Requires client authentication (Basic or POST). PKCE validation for authorization_code grant.
 * @summary OAuth 2.1 Token Endpoint
 */
export const oAuthControllerTokenResponseTokenTypeDefault = 'Bearer';

export const oAuthControllerTokenResponse = zod.object({
  access_token: zod.string().describe('The access token (JWT)'),
  token_type: zod.string().describe('Token type (always \"Bearer\")'),
  expires_in: zod.number().describe('Token expiration time in seconds'),
  refresh_token: zod
    .string()
    .optional()
    .describe('Refresh token (if applicable)'),
  scope: zod.string().optional().describe('Granted scopes (space-separated)'),
});

/**
 * Generates authorization code with PKCE for mobile clients or via PAR for confidential clients. Supports request_uri from POST /oauth/par (RFC 9126). Requires system browser (no embedded WebViews per RFC 8252). Redirects to redirect_uri with code and state parameters.
 * @summary OAuth 2.1 Authorization Endpoint
 */
export const authorizeControllerAuthorizeQueryParams = zod.object({
  request_uri: zod.string().optional().describe('PAR request URI (RFC 9126)'),
  response_type: zod
    .enum(['code'])
    .optional()
    .describe('Response type (only \"code\" supported)'),
  client_id: zod.string().optional().describe('Client ID'),
  redirect_uri: zod
    .string()
    .optional()
    .describe('Redirect URI (must be pre-registered)'),
  code_challenge: zod.string().optional().describe('PKCE code challenge'),
  code_challenge_method: zod
    .enum(['S256'])
    .optional()
    .describe('PKCE code challenge method (only S256 supported)'),
  state: zod
    .string()
    .optional()
    .describe(
      'State parameter for CSRF protection (mandatory for direct requests)'
    ),
  scope: zod.string().optional().describe('Requested scopes (space-separated)'),
});

/**
 * Verifies mobile device legitimacy via iOS App Attest or Android Play Integrity. Returns short-lived attestation token for use in authorization code exchange.
 * @summary Device Attestation for Mobile Clients
 */
export const attestControllerAttestBodyNonceMin = 16;

export const attestControllerAttestBody = zod.object({
  client_id: zod.string().describe('OAuth 2.0 Client ID (must be mobile type)'),
  platform: zod.enum(['ios', 'android']).describe('Platform identifier'),
  nonce: zod
    .string()
    .min(attestControllerAttestBodyNonceMin)
    .describe('Base64url-encoded nonce (minimum 128 bits)'),
  attestation_token: zod
    .string()
    .describe(
      'Platform-specific attestation token (iOS: App Attest, Android: Play Integrity)'
    ),
});

export const attestControllerAttestResponseTokenTypeDefault = 'Bearer';

export const attestControllerAttestResponse = zod.object({
  attestation_token: zod
    .string()
    .describe('Short-lived attestation token for use in /oauth/token'),
  token_type: zod.string().describe('Token type'),
  expires_in: zod.number().describe('Token expiry in seconds'),
});

/**
 * Validates access tokens and returns metadata. Requires confidential client authentication (Basic Auth).
 * @summary Token Introspection (RFC 7662)
 */
export const oAuthControllerIntrospectResponse = zod.object({
  active: zod.boolean().describe('Whether the token is currently active'),
  scope: zod
    .string()
    .optional()
    .describe('Scopes associated with the token (space-separated)'),
  client_id: zod.string().optional().describe('Client ID'),
  username: zod.string().optional().describe('Username (email or user ID)'),
  token_type: zod.string().optional().describe('Token type'),
  exp: zod.number().optional().describe('Expiration timestamp (Unix time)'),
  iat: zod.number().optional().describe('Issued at timestamp (Unix time)'),
  nbf: zod.number().optional().describe('Not before timestamp (Unix time)'),
  sub: zod.string().optional().describe('Subject (user ID)'),
  aud: zod.string().optional().describe('Audience'),
  iss: zod.string().optional().describe('Issuer'),
  jti: zod.string().optional().describe('JWT ID'),
});

/**
 * Allows confidential clients to push authorization parameters to the server before redirecting the user. Returns a request_uri to use in /oauth/authorize. Requires client authentication (HTTP Basic or POST body).
 * @summary Pushed Authorization Request (RFC 9126)
 */
export const pARControllerPushAuthorizationRequestBody = zod.object({
  response_type: zod
    .enum(['code'])
    .describe('Response type (only \"code\" supported)'),
  client_id: zod.string().describe('Client ID'),
  redirect_uri: zod.string().describe('Redirect URI (must be pre-registered)'),
  code_challenge: zod
    .string()
    .optional()
    .describe('PKCE code challenge (optional for confidential clients)'),
  code_challenge_method: zod
    .enum(['S256'])
    .optional()
    .describe('PKCE code challenge method'),
  state: zod
    .string()
    .optional()
    .describe('State parameter for CSRF protection (recommended)'),
  scope: zod.string().optional().describe('Requested scopes (space-separated)'),
});
