/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  OAuthErrorResponseDto,
  UserInfoResponseDto
} from '../kodkafaApi.schemas';

import { clientMutator } from '../../../lib/api/client.mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns user claims based on access token scopes. Requires "openid" scope. Additional claims returned based on "profile", "email", "phone", and "address" scopes.
 * @summary OIDC UserInfo Endpoint
 */
export type userInfoControllerGetUserInfoResponse200 = {
  data: UserInfoResponseDto
  status: 200
}

export type userInfoControllerGetUserInfoResponse401 = {
  data: OAuthErrorResponseDto
  status: 401
}
    
export type userInfoControllerGetUserInfoResponseSuccess = (userInfoControllerGetUserInfoResponse200) & {
  headers: Headers;
};
export type userInfoControllerGetUserInfoResponseError = (userInfoControllerGetUserInfoResponse401) & {
  headers: Headers;
};

export type userInfoControllerGetUserInfoResponse = (userInfoControllerGetUserInfoResponseSuccess | userInfoControllerGetUserInfoResponseError)

export const getUserInfoControllerGetUserInfoUrl = () => {


  

  return `/api/oauth/userinfo`
}

export const userInfoControllerGetUserInfo = async ( options?: RequestInit): Promise<userInfoControllerGetUserInfoResponse> => {
  
  return clientMutator<userInfoControllerGetUserInfoResponse>(getUserInfoControllerGetUserInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getUserInfoControllerGetUserInfoInfiniteQueryKey = () => {
    return [
    'infinite', `/api/oauth/userinfo`
    ] as const;
    }

export const getUserInfoControllerGetUserInfoQueryKey = () => {
    return [
    `/api/oauth/userinfo`
    ] as const;
    }

    
export const getUserInfoControllerGetUserInfoInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>>, TError = OAuthErrorResponseDto>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserInfoControllerGetUserInfoInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>> = ({ signal }) => userInfoControllerGetUserInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 30000, gcTime: 300000, retry: 2, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserInfoControllerGetUserInfoInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>>
export type UserInfoControllerGetUserInfoInfiniteQueryError = OAuthErrorResponseDto


export function useUserInfoControllerGetUserInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>>, TError = OAuthErrorResponseDto>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>,
          TError,
          Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserInfoControllerGetUserInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>>, TError = OAuthErrorResponseDto>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>,
          TError,
          Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserInfoControllerGetUserInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>>, TError = OAuthErrorResponseDto>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary OIDC UserInfo Endpoint
 */

export function useUserInfoControllerGetUserInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>>, TError = OAuthErrorResponseDto>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserInfoControllerGetUserInfoInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getUserInfoControllerGetUserInfoQueryOptions = <TData = Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError = OAuthErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserInfoControllerGetUserInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>> = ({ signal }) => userInfoControllerGetUserInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 30000, gcTime: 300000, retry: 2, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserInfoControllerGetUserInfoQueryResult = NonNullable<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>>
export type UserInfoControllerGetUserInfoQueryError = OAuthErrorResponseDto


export function useUserInfoControllerGetUserInfo<TData = Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError = OAuthErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>,
          TError,
          Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserInfoControllerGetUserInfo<TData = Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError = OAuthErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>,
          TError,
          Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserInfoControllerGetUserInfo<TData = Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError = OAuthErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary OIDC UserInfo Endpoint
 */

export function useUserInfoControllerGetUserInfo<TData = Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError = OAuthErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userInfoControllerGetUserInfo>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserInfoControllerGetUserInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




