/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import * as zod from 'zod';


/**
 * @summary Get all posts with pagination
 */
export const postsQueryControllerFindAllQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of items to return (1-100, default: 20)'),
  "after": zod.string().optional().describe('Cursor token for next page (forward pagination)'),
  "before": zod.string().optional().describe('Cursor token for previous page (backward pagination)'),
  "sort": zod.enum(['title', 'slug', 'createdAt', 'updatedAt', '-title', '-slug', '-createdAt', '-updatedAt']).optional().describe('Sort field with optional \'-\' prefix for descending. Allowed fields: title, slug, createdAt, updatedAt'),
  "projectId": zod.string().optional().describe('Filter by projectId'),
  "domain": zod.string().optional().describe('Filter by domain (exact match)'),
  "domain.contains": zod.string().optional().describe('Filter where domain contains the value (case-sensitive)'),
  "domain.icontains": zod.string().optional().describe('Filter where domain contains the value (case-insensitive)'),
  "domain.startsWith": zod.string().optional().describe('Filter where domain starts with the value (case-sensitive)'),
  "domain.istartswith": zod.string().optional().describe('Filter where domain starts with the value (case-insensitive)'),
  "title": zod.string().optional().describe('Filter by title (exact match)'),
  "title.contains": zod.string().optional().describe('Filter where title contains the value (case-sensitive)'),
  "title.icontains": zod.string().optional().describe('Filter where title contains the value (case-insensitive)'),
  "title.startsWith": zod.string().optional().describe('Filter where title starts with the value (case-sensitive)'),
  "title.istartswith": zod.string().optional().describe('Filter where title starts with the value (case-insensitive)'),
  "slug": zod.string().optional().describe('Filter by slug (exact match)'),
  "slug.contains": zod.string().optional().describe('Filter where slug contains the value (case-sensitive)'),
  "slug.icontains": zod.string().optional().describe('Filter where slug contains the value (case-insensitive)'),
  "slug.startsWith": zod.string().optional().describe('Filter where slug starts with the value (case-sensitive)'),
  "slug.istartswith": zod.string().optional().describe('Filter where slug starts with the value (case-insensitive)'),
  "description": zod.string().optional().describe('Filter by description (exact match)'),
  "description.contains": zod.string().optional().describe('Filter where description contains the value (case-sensitive)'),
  "description.icontains": zod.string().optional().describe('Filter where description contains the value (case-insensitive)'),
  "description.startsWith": zod.string().optional().describe('Filter where description starts with the value (case-sensitive)'),
  "description.istartswith": zod.string().optional().describe('Filter where description starts with the value (case-insensitive)'),
  "tags": zod.string().optional().describe('Filter by tags (exact match)'),
  "tags.contains": zod.string().optional().describe('Filter where tags contains the value (case-sensitive)'),
  "tags.icontains": zod.string().optional().describe('Filter where tags contains the value (case-insensitive)'),
  "tags.startsWith": zod.string().optional().describe('Filter where tags starts with the value (case-sensitive)'),
  "tags.istartswith": zod.string().optional().describe('Filter where tags starts with the value (case-insensitive)'),
  "type": zod.string().optional().describe('Filter by type (exact match)'),
  "type.contains": zod.string().optional().describe('Filter where type contains the value (case-sensitive)'),
  "type.icontains": zod.string().optional().describe('Filter where type contains the value (case-insensitive)'),
  "type.startsWith": zod.string().optional().describe('Filter where type starts with the value (case-sensitive)'),
  "type.istartswith": zod.string().optional().describe('Filter where type starts with the value (case-insensitive)'),
  "status": zod.string().optional().describe('Filter by status (exact match)'),
  "status.contains": zod.string().optional().describe('Filter where status contains the value (case-sensitive)'),
  "status.icontains": zod.string().optional().describe('Filter where status contains the value (case-insensitive)'),
  "status.startsWith": zod.string().optional().describe('Filter where status starts with the value (case-sensitive)'),
  "status.istartswith": zod.string().optional().describe('Filter where status starts with the value (case-insensitive)'),
  "authorId": zod.string().optional().describe('Filter by authorId'),
  "categories": zod.string().optional().describe('Filter by categories'),
  "createdAt": zod.string().optional().describe('Filter by createdAt (exact match, ISO date string for dates)'),
  "createdAt.gt": zod.string().optional().describe('Filter where createdAt is greater than'),
  "createdAt.gte": zod.string().optional().describe('Filter where createdAt is greater than or equal'),
  "createdAt.lt": zod.string().optional().describe('Filter where createdAt is less than'),
  "createdAt.lte": zod.string().optional().describe('Filter where createdAt is less than or equal'),
  "updatedAt": zod.string().optional().describe('Filter by updatedAt (exact match, ISO date string for dates)'),
  "updatedAt.gt": zod.string().optional().describe('Filter where updatedAt is greater than'),
  "updatedAt.gte": zod.string().optional().describe('Filter where updatedAt is greater than or equal'),
  "updatedAt.lt": zod.string().optional().describe('Filter where updatedAt is less than'),
  "updatedAt.lte": zod.string().optional().describe('Filter where updatedAt is less than or equal')
})

export const postsQueryControllerFindAllResponseItemsItemProjectIdMin = 24;
export const postsQueryControllerFindAllResponseItemsItemProjectIdMax = 24;

export const postsQueryControllerFindAllResponseItemsItemDomainMax = 30;

export const postsQueryControllerFindAllResponseItemsItemTitleMin = 5;
export const postsQueryControllerFindAllResponseItemsItemTitleMax = 120;

export const postsQueryControllerFindAllResponseItemsItemSlugMin = 5;
export const postsQueryControllerFindAllResponseItemsItemSlugMax = 120;

export const postsQueryControllerFindAllResponseItemsItemDescriptionMin = 10;
export const postsQueryControllerFindAllResponseItemsItemDescriptionMax = 500;

export const postsQueryControllerFindAllResponseItemsItemIdMin = 24;
export const postsQueryControllerFindAllResponseItemsItemIdMax = 24;

export const postsQueryControllerFindAllResponseItemsItemAuthorIdMin = 24;
export const postsQueryControllerFindAllResponseItemsItemAuthorIdMax = 24;

export const postsQueryControllerFindAllResponseItemsItemFilesItemLocationTypeDefault = "Point";export const postsQueryControllerFindAllResponseItemsItemFilesItemIdMin = 24;
export const postsQueryControllerFindAllResponseItemsItemFilesItemIdMax = 24;

export const postsQueryControllerFindAllResponseItemsItemAuthorIdMinOne = 24;
export const postsQueryControllerFindAllResponseItemsItemAuthorIdMaxOne = 24;



export const postsQueryControllerFindAllResponse = zod.object({
  "items": zod.array(zod.object({
  "createdAt": zod.string().datetime({}),
  "updatedAt": zod.string().datetime({}),
  "projectId": zod.string().min(postsQueryControllerFindAllResponseItemsItemProjectIdMin).max(postsQueryControllerFindAllResponseItemsItemProjectIdMax).describe('The unique id'),
  "domain": zod.string().max(postsQueryControllerFindAllResponseItemsItemDomainMax).describe('Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'),
  "title": zod.string().min(postsQueryControllerFindAllResponseItemsItemTitleMin).max(postsQueryControllerFindAllResponseItemsItemTitleMax),
  "slug": zod.string().min(postsQueryControllerFindAllResponseItemsItemSlugMin).max(postsQueryControllerFindAllResponseItemsItemSlugMax),
  "description": zod.string().min(postsQueryControllerFindAllResponseItemsItemDescriptionMin).max(postsQueryControllerFindAllResponseItemsItemDescriptionMax).optional(),
  "content": zod.string().optional(),
  "tags": zod.array(zod.string()).optional(),
  "type": zod.enum(['category', 'post', 'article']).optional(),
  "status": zod.enum(['draft', 'hidden', 'pending', 'scheduled', 'paused', 'active', 'completed', 'published', 'cancelled', 'expired', 'accepted', 'rejected']).optional(),
  "id": zod.string().min(postsQueryControllerFindAllResponseItemsItemIdMin).max(postsQueryControllerFindAllResponseItemsItemIdMax).describe('The unique id'),
  "authorId": zod.string().min(postsQueryControllerFindAllResponseItemsItemAuthorIdMin).max(postsQueryControllerFindAllResponseItemsItemAuthorIdMax).describe('The unique id of the author'),
  "files": zod.array(zod.object({
  "altText": zod.string(),
  "exif": zod.object({
  "Model": zod.string(),
  "Lens": zod.string(),
  "ISOSpeedRatings": zod.string(),
  "FocalLength": zod.string(),
  "FNumber": zod.string(),
  "ExposureTime": zod.string(),
  "WhiteBalance": zod.string(),
  "MeteringMode": zod.string(),
  "DateTime": zod.string(),
  "GPSLatitude": zod.string(),
  "GPSLongitude": zod.string()
}).optional(),
  "location": zod.object({
  "type": zod.string(),
  "coordinates": zod.array(zod.number())
}).optional(),
  "src": zod.string(),
  "type": zod.string(),
  "id": zod.string().min(postsQueryControllerFindAllResponseItemsItemFilesItemIdMin).max(postsQueryControllerFindAllResponseItemsItemFilesItemIdMax).describe('The unique id')
})).optional().describe('Post files (origin field excluded)'),
  "author": zod.object({
  "id": zod.string().min(postsQueryControllerFindAllResponseItemsItemAuthorIdMinOne).max(postsQueryControllerFindAllResponseItemsItemAuthorIdMaxOne).describe('The unique id of the author'),
  "name": zod.string().describe('Author name'),
  "username": zod.string().optional().describe('Author username (falls back to userId if username not found)')
}).optional().describe('Post author information (populated)'),
  "categories": zod.array(zod.object({
  "id": zod.string().describe('The unique id'),
  "slug": zod.string().describe('Category slug'),
  "title": zod.string().describe('Category title')
})).optional().describe('Post categories (populated)')
})).optional(),
  "meta": zod.object({
  "nextCursor": zod.string().optional(),
  "prevCursor": zod.string().optional(),
  "hasNextPage": zod.boolean(),
  "hasPrevPage": zod.boolean(),
  "limit": zod.number(),
  "sort": zod.string(),
  "order": zod.enum(['asc', 'desc'])
}).optional()
})

/**
 * @summary Get published posts for sitemap generation
 */
export const postsQueryControllerFindSitemapQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of items to return (1-100, default: 20)'),
  "after": zod.string().optional().describe('Cursor token for next page (forward pagination)'),
  "before": zod.string().optional().describe('Cursor token for previous page (backward pagination)'),
  "sort": zod.enum(['title', 'slug', 'createdAt', 'updatedAt', '-title', '-slug', '-createdAt', '-updatedAt']).optional().describe('Sort field with optional \'-\' prefix for descending. Allowed fields: title, slug, createdAt, updatedAt'),
  "projectId": zod.string().optional().describe('Filter by projectId'),
  "domain": zod.string().optional().describe('Filter by domain (exact match)'),
  "domain.contains": zod.string().optional().describe('Filter where domain contains the value (case-sensitive)'),
  "domain.icontains": zod.string().optional().describe('Filter where domain contains the value (case-insensitive)'),
  "domain.startsWith": zod.string().optional().describe('Filter where domain starts with the value (case-sensitive)'),
  "domain.istartswith": zod.string().optional().describe('Filter where domain starts with the value (case-insensitive)'),
  "title": zod.string().optional().describe('Filter by title (exact match)'),
  "title.contains": zod.string().optional().describe('Filter where title contains the value (case-sensitive)'),
  "title.icontains": zod.string().optional().describe('Filter where title contains the value (case-insensitive)'),
  "title.startsWith": zod.string().optional().describe('Filter where title starts with the value (case-sensitive)'),
  "title.istartswith": zod.string().optional().describe('Filter where title starts with the value (case-insensitive)'),
  "slug": zod.string().optional().describe('Filter by slug (exact match)'),
  "slug.contains": zod.string().optional().describe('Filter where slug contains the value (case-sensitive)'),
  "slug.icontains": zod.string().optional().describe('Filter where slug contains the value (case-insensitive)'),
  "slug.startsWith": zod.string().optional().describe('Filter where slug starts with the value (case-sensitive)'),
  "slug.istartswith": zod.string().optional().describe('Filter where slug starts with the value (case-insensitive)'),
  "description": zod.string().optional().describe('Filter by description (exact match)'),
  "description.contains": zod.string().optional().describe('Filter where description contains the value (case-sensitive)'),
  "description.icontains": zod.string().optional().describe('Filter where description contains the value (case-insensitive)'),
  "description.startsWith": zod.string().optional().describe('Filter where description starts with the value (case-sensitive)'),
  "description.istartswith": zod.string().optional().describe('Filter where description starts with the value (case-insensitive)'),
  "tags": zod.string().optional().describe('Filter by tags (exact match)'),
  "tags.contains": zod.string().optional().describe('Filter where tags contains the value (case-sensitive)'),
  "tags.icontains": zod.string().optional().describe('Filter where tags contains the value (case-insensitive)'),
  "tags.startsWith": zod.string().optional().describe('Filter where tags starts with the value (case-sensitive)'),
  "tags.istartswith": zod.string().optional().describe('Filter where tags starts with the value (case-insensitive)'),
  "type": zod.string().optional().describe('Filter by type (exact match)'),
  "type.contains": zod.string().optional().describe('Filter where type contains the value (case-sensitive)'),
  "type.icontains": zod.string().optional().describe('Filter where type contains the value (case-insensitive)'),
  "type.startsWith": zod.string().optional().describe('Filter where type starts with the value (case-sensitive)'),
  "type.istartswith": zod.string().optional().describe('Filter where type starts with the value (case-insensitive)'),
  "status": zod.string().optional().describe('Filter by status (exact match)'),
  "status.contains": zod.string().optional().describe('Filter where status contains the value (case-sensitive)'),
  "status.icontains": zod.string().optional().describe('Filter where status contains the value (case-insensitive)'),
  "status.startsWith": zod.string().optional().describe('Filter where status starts with the value (case-sensitive)'),
  "status.istartswith": zod.string().optional().describe('Filter where status starts with the value (case-insensitive)'),
  "authorId": zod.string().optional().describe('Filter by authorId'),
  "categories": zod.string().optional().describe('Filter by categories'),
  "createdAt": zod.string().optional().describe('Filter by createdAt (exact match, ISO date string for dates)'),
  "createdAt.gt": zod.string().optional().describe('Filter where createdAt is greater than'),
  "createdAt.gte": zod.string().optional().describe('Filter where createdAt is greater than or equal'),
  "createdAt.lt": zod.string().optional().describe('Filter where createdAt is less than'),
  "createdAt.lte": zod.string().optional().describe('Filter where createdAt is less than or equal'),
  "updatedAt": zod.string().optional().describe('Filter by updatedAt (exact match, ISO date string for dates)'),
  "updatedAt.gt": zod.string().optional().describe('Filter where updatedAt is greater than'),
  "updatedAt.gte": zod.string().optional().describe('Filter where updatedAt is greater than or equal'),
  "updatedAt.lt": zod.string().optional().describe('Filter where updatedAt is less than'),
  "updatedAt.lte": zod.string().optional().describe('Filter where updatedAt is less than or equal')
})

export const postsQueryControllerFindSitemapResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('The unique id'),
  "domain": zod.string().describe('Domain label for multi-site support'),
  "slug": zod.string().describe('Post slug for URL construction'),
  "updatedAt": zod.string().datetime({}).describe('Last modification date for sitemap lastmod')
})).optional(),
  "meta": zod.object({
  "nextCursor": zod.string().optional(),
  "prevCursor": zod.string().optional(),
  "hasNextPage": zod.boolean(),
  "hasPrevPage": zod.boolean(),
  "limit": zod.number(),
  "sort": zod.string(),
  "order": zod.enum(['asc', 'desc'])
}).optional()
})

