/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import * as zod from 'zod';


/**
 * Generates the appropriate authentication URL for the specified social provider (e.g., Google, GitHub). The client should redirect the user to this URL.
 * @summary Get OAuth URL for a social provider
 */
export const socialAuthControllerGetSocialAuthUrlParams = zod.object({
  "provider": zod.enum(['google', 'github', 'apple']).describe('The social provider to authenticate with.')
})

export const socialAuthControllerGetSocialAuthUrlResponse = zod.object({
  "url": zod.string().describe('OAuth URL for social login')
})

/**
 * This endpoint is the redirect URI for the social provider. It exchanges the authorization code for user profile information, finds or creates a local user, and returns authentication tokens.
 * @summary Handle the callback from the social provider
 */
export const socialAuthControllerSocialAuthCallbackParams = zod.object({
  "provider": zod.enum(['google', 'github', 'apple']).describe('The social provider calling back.')
})

export const socialAuthControllerSocialAuthCallbackBody = zod.object({
  "code": zod.string().describe('code from the social provider'),
  "state": zod.string().describe('state from the social provider')
})

export const socialAuthControllerSocialAuthCallbackResponse = zod.object({
  "accessToken": zod.string(),
  "expiresIn": zod.number()
})

