/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type {
  ErrorResponseDto,
  PostsAnalyticsControllerGetPostStatistics200,
  TagCloudDto,
} from ".././schemas";

import { customInstance } from ".././mutator";

/**
 * @summary Get tag cloud
 */
export type postsAnalyticsControllerGetTagCloudResponse200 = {
  data: TagCloudDto[];
  status: 200;
};

export type postsAnalyticsControllerGetTagCloudResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type postsAnalyticsControllerGetTagCloudResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type postsAnalyticsControllerGetTagCloudResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type postsAnalyticsControllerGetTagCloudResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type postsAnalyticsControllerGetTagCloudResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type postsAnalyticsControllerGetTagCloudResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type postsAnalyticsControllerGetTagCloudResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type postsAnalyticsControllerGetTagCloudResponseSuccess =
  postsAnalyticsControllerGetTagCloudResponse200 & {
    headers: Headers;
  };
export type postsAnalyticsControllerGetTagCloudResponseError = (
  | postsAnalyticsControllerGetTagCloudResponse400
  | postsAnalyticsControllerGetTagCloudResponse401
  | postsAnalyticsControllerGetTagCloudResponse403
  | postsAnalyticsControllerGetTagCloudResponse404
  | postsAnalyticsControllerGetTagCloudResponse409
  | postsAnalyticsControllerGetTagCloudResponse422
  | postsAnalyticsControllerGetTagCloudResponse500
) & {
  headers: Headers;
};

export type postsAnalyticsControllerGetTagCloudResponse =
  | postsAnalyticsControllerGetTagCloudResponseSuccess
  | postsAnalyticsControllerGetTagCloudResponseError;

export const getPostsAnalyticsControllerGetTagCloudUrl = () => {
  return `/posts/analytics/tag-cloud`;
};

export const postsAnalyticsControllerGetTagCloud = async (
  options?: RequestInit,
): Promise<postsAnalyticsControllerGetTagCloudResponse> => {
  return customInstance<postsAnalyticsControllerGetTagCloudResponse>(
    getPostsAnalyticsControllerGetTagCloudUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get tag cloud by domain
 */
export type postsAnalyticsControllerGetTagCloudByDomainResponse200 = {
  data: TagCloudDto[];
  status: 200;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponseSuccess =
  postsAnalyticsControllerGetTagCloudByDomainResponse200 & {
    headers: Headers;
  };
export type postsAnalyticsControllerGetTagCloudByDomainResponseError = (
  | postsAnalyticsControllerGetTagCloudByDomainResponse400
  | postsAnalyticsControllerGetTagCloudByDomainResponse401
  | postsAnalyticsControllerGetTagCloudByDomainResponse403
  | postsAnalyticsControllerGetTagCloudByDomainResponse404
  | postsAnalyticsControllerGetTagCloudByDomainResponse409
  | postsAnalyticsControllerGetTagCloudByDomainResponse422
  | postsAnalyticsControllerGetTagCloudByDomainResponse500
) & {
  headers: Headers;
};

export type postsAnalyticsControllerGetTagCloudByDomainResponse =
  | postsAnalyticsControllerGetTagCloudByDomainResponseSuccess
  | postsAnalyticsControllerGetTagCloudByDomainResponseError;

export const getPostsAnalyticsControllerGetTagCloudByDomainUrl = (
  domain: string,
) => {
  return `/posts/analytics/tag-cloud/${domain}`;
};

export const postsAnalyticsControllerGetTagCloudByDomain = async (
  domain: string,
  options?: RequestInit,
): Promise<postsAnalyticsControllerGetTagCloudByDomainResponse> => {
  return customInstance<postsAnalyticsControllerGetTagCloudByDomainResponse>(
    getPostsAnalyticsControllerGetTagCloudByDomainUrl(domain),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get tag cloud by category
 */
export type postsAnalyticsControllerGetTagCloudByCategoryResponse200 = {
  data: TagCloudDto[];
  status: 200;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponseSuccess =
  postsAnalyticsControllerGetTagCloudByCategoryResponse200 & {
    headers: Headers;
  };
export type postsAnalyticsControllerGetTagCloudByCategoryResponseError = (
  | postsAnalyticsControllerGetTagCloudByCategoryResponse400
  | postsAnalyticsControllerGetTagCloudByCategoryResponse401
  | postsAnalyticsControllerGetTagCloudByCategoryResponse403
  | postsAnalyticsControllerGetTagCloudByCategoryResponse404
  | postsAnalyticsControllerGetTagCloudByCategoryResponse409
  | postsAnalyticsControllerGetTagCloudByCategoryResponse422
  | postsAnalyticsControllerGetTagCloudByCategoryResponse500
) & {
  headers: Headers;
};

export type postsAnalyticsControllerGetTagCloudByCategoryResponse =
  | postsAnalyticsControllerGetTagCloudByCategoryResponseSuccess
  | postsAnalyticsControllerGetTagCloudByCategoryResponseError;

export const getPostsAnalyticsControllerGetTagCloudByCategoryUrl = (
  category: string,
) => {
  return `/posts/analytics/tag-cloud/category/${category}`;
};

export const postsAnalyticsControllerGetTagCloudByCategory = async (
  category: string,
  options?: RequestInit,
): Promise<postsAnalyticsControllerGetTagCloudByCategoryResponse> => {
  return customInstance<postsAnalyticsControllerGetTagCloudByCategoryResponse>(
    getPostsAnalyticsControllerGetTagCloudByCategoryUrl(category),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get tag cloud by category and domain
 */
export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse200 =
  {
    data: TagCloudDto[];
    status: 200;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse400 =
  {
    data: ErrorResponseDto;
    status: 400;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse401 =
  {
    data: ErrorResponseDto;
    status: 401;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse403 =
  {
    data: ErrorResponseDto;
    status: 403;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse404 =
  {
    data: ErrorResponseDto;
    status: 404;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse409 =
  {
    data: ErrorResponseDto;
    status: 409;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse422 =
  {
    data: ErrorResponseDto;
    status: 422;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse500 =
  {
    data: ErrorResponseDto;
    status: 500;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponseSuccess =
  postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse200 & {
    headers: Headers;
  };
export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponseError =
  (
    | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse400
    | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse401
    | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse403
    | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse404
    | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse409
    | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse422
    | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse500
  ) & {
    headers: Headers;
  };

export type postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse =
  | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponseSuccess
  | postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponseError;

export const getPostsAnalyticsControllerGetTagCloudByCategoryAndDomainUrl = (
  category: string,
  domain: string,
) => {
  return `/posts/analytics/tag-cloud/category/${category}/domain/${domain}`;
};

export const postsAnalyticsControllerGetTagCloudByCategoryAndDomain = async (
  category: string,
  domain: string,
  options?: RequestInit,
): Promise<postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse> => {
  return customInstance<postsAnalyticsControllerGetTagCloudByCategoryAndDomainResponse>(
    getPostsAnalyticsControllerGetTagCloudByCategoryAndDomainUrl(
      category,
      domain,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get posts statistics
 */
export type postsAnalyticsControllerGetPostStatisticsResponse200 = {
  data: PostsAnalyticsControllerGetPostStatistics200;
  status: 200;
};

export type postsAnalyticsControllerGetPostStatisticsResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type postsAnalyticsControllerGetPostStatisticsResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type postsAnalyticsControllerGetPostStatisticsResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type postsAnalyticsControllerGetPostStatisticsResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type postsAnalyticsControllerGetPostStatisticsResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type postsAnalyticsControllerGetPostStatisticsResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type postsAnalyticsControllerGetPostStatisticsResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type postsAnalyticsControllerGetPostStatisticsResponseSuccess =
  postsAnalyticsControllerGetPostStatisticsResponse200 & {
    headers: Headers;
  };
export type postsAnalyticsControllerGetPostStatisticsResponseError = (
  | postsAnalyticsControllerGetPostStatisticsResponse400
  | postsAnalyticsControllerGetPostStatisticsResponse401
  | postsAnalyticsControllerGetPostStatisticsResponse403
  | postsAnalyticsControllerGetPostStatisticsResponse404
  | postsAnalyticsControllerGetPostStatisticsResponse409
  | postsAnalyticsControllerGetPostStatisticsResponse422
  | postsAnalyticsControllerGetPostStatisticsResponse500
) & {
  headers: Headers;
};

export type postsAnalyticsControllerGetPostStatisticsResponse =
  | postsAnalyticsControllerGetPostStatisticsResponseSuccess
  | postsAnalyticsControllerGetPostStatisticsResponseError;

export const getPostsAnalyticsControllerGetPostStatisticsUrl = () => {
  return `/posts/analytics/statistics`;
};

export const postsAnalyticsControllerGetPostStatistics = async (
  options?: RequestInit,
): Promise<postsAnalyticsControllerGetPostStatisticsResponse> => {
  return customInstance<postsAnalyticsControllerGetPostStatisticsResponse>(
    getPostsAnalyticsControllerGetPostStatisticsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get popular tags
 */
export type postsAnalyticsControllerGetPopularTagsResponse200 = {
  data: TagCloudDto[];
  status: 200;
};

export type postsAnalyticsControllerGetPopularTagsResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type postsAnalyticsControllerGetPopularTagsResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type postsAnalyticsControllerGetPopularTagsResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type postsAnalyticsControllerGetPopularTagsResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type postsAnalyticsControllerGetPopularTagsResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type postsAnalyticsControllerGetPopularTagsResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type postsAnalyticsControllerGetPopularTagsResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type postsAnalyticsControllerGetPopularTagsResponseSuccess =
  postsAnalyticsControllerGetPopularTagsResponse200 & {
    headers: Headers;
  };
export type postsAnalyticsControllerGetPopularTagsResponseError = (
  | postsAnalyticsControllerGetPopularTagsResponse400
  | postsAnalyticsControllerGetPopularTagsResponse401
  | postsAnalyticsControllerGetPopularTagsResponse403
  | postsAnalyticsControllerGetPopularTagsResponse404
  | postsAnalyticsControllerGetPopularTagsResponse409
  | postsAnalyticsControllerGetPopularTagsResponse422
  | postsAnalyticsControllerGetPopularTagsResponse500
) & {
  headers: Headers;
};

export type postsAnalyticsControllerGetPopularTagsResponse =
  | postsAnalyticsControllerGetPopularTagsResponseSuccess
  | postsAnalyticsControllerGetPopularTagsResponseError;

export const getPostsAnalyticsControllerGetPopularTagsUrl = () => {
  return `/posts/analytics/popular-tags`;
};

export const postsAnalyticsControllerGetPopularTags = async (
  options?: RequestInit,
): Promise<postsAnalyticsControllerGetPopularTagsResponse> => {
  return customInstance<postsAnalyticsControllerGetPopularTagsResponse>(
    getPostsAnalyticsControllerGetPopularTagsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};
