/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthDto,
  SocialCallbackDto,
  SocialUrlDto
} from '../kodkafaApi.schemas';

import { clientMutator } from '../../../lib/api/client.mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Generates the appropriate authentication URL for the specified social provider (e.g., Google, GitHub). The client should redirect the user to this URL.
 * @summary Get OAuth URL for a social provider
 */
export type socialAuthControllerGetSocialAuthUrlResponse200 = {
  data: SocialUrlDto
  status: 200
}
    
export type socialAuthControllerGetSocialAuthUrlResponseSuccess = (socialAuthControllerGetSocialAuthUrlResponse200) & {
  headers: Headers;
};
;

export type socialAuthControllerGetSocialAuthUrlResponse = (socialAuthControllerGetSocialAuthUrlResponseSuccess)

export const getSocialAuthControllerGetSocialAuthUrlUrl = (provider: 'google' | 'github' | 'apple',) => {


  

  return `/api/social/${provider}/url`
}

export const socialAuthControllerGetSocialAuthUrl = async (provider: 'google' | 'github' | 'apple', options?: RequestInit): Promise<socialAuthControllerGetSocialAuthUrlResponse> => {
  
  return clientMutator<socialAuthControllerGetSocialAuthUrlResponse>(getSocialAuthControllerGetSocialAuthUrlUrl(provider),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSocialAuthControllerGetSocialAuthUrlInfiniteQueryKey = (provider?: 'google' | 'github' | 'apple',) => {
    return [
    'infinite', `/api/social/${provider}/url`
    ] as const;
    }

export const getSocialAuthControllerGetSocialAuthUrlQueryKey = (provider?: 'google' | 'github' | 'apple',) => {
    return [
    `/api/social/${provider}/url`
    ] as const;
    }

    
export const getSocialAuthControllerGetSocialAuthUrlInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>>, TError = unknown>(provider: 'google' | 'github' | 'apple', options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSocialAuthControllerGetSocialAuthUrlInfiniteQueryKey(provider);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>> = ({ signal }) => socialAuthControllerGetSocialAuthUrl(provider, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(provider),  staleTime: 30000, gcTime: 300000, retry: 2, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SocialAuthControllerGetSocialAuthUrlInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>>
export type SocialAuthControllerGetSocialAuthUrlInfiniteQueryError = unknown


export function useSocialAuthControllerGetSocialAuthUrlInfinite<TData = InfiniteData<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>>, TError = unknown>(
 provider: 'google' | 'github' | 'apple', options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>,
          TError,
          Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSocialAuthControllerGetSocialAuthUrlInfinite<TData = InfiniteData<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>>, TError = unknown>(
 provider: 'google' | 'github' | 'apple', options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>,
          TError,
          Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSocialAuthControllerGetSocialAuthUrlInfinite<TData = InfiniteData<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>>, TError = unknown>(
 provider: 'google' | 'github' | 'apple', options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get OAuth URL for a social provider
 */

export function useSocialAuthControllerGetSocialAuthUrlInfinite<TData = InfiniteData<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>>, TError = unknown>(
 provider: 'google' | 'github' | 'apple', options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSocialAuthControllerGetSocialAuthUrlInfiniteQueryOptions(provider,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getSocialAuthControllerGetSocialAuthUrlQueryOptions = <TData = Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError = unknown>(provider: 'google' | 'github' | 'apple', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSocialAuthControllerGetSocialAuthUrlQueryKey(provider);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>> = ({ signal }) => socialAuthControllerGetSocialAuthUrl(provider, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(provider),  staleTime: 30000, gcTime: 300000, retry: 2, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SocialAuthControllerGetSocialAuthUrlQueryResult = NonNullable<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>>
export type SocialAuthControllerGetSocialAuthUrlQueryError = unknown


export function useSocialAuthControllerGetSocialAuthUrl<TData = Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError = unknown>(
 provider: 'google' | 'github' | 'apple', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>,
          TError,
          Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSocialAuthControllerGetSocialAuthUrl<TData = Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError = unknown>(
 provider: 'google' | 'github' | 'apple', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>,
          TError,
          Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSocialAuthControllerGetSocialAuthUrl<TData = Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError = unknown>(
 provider: 'google' | 'github' | 'apple', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get OAuth URL for a social provider
 */

export function useSocialAuthControllerGetSocialAuthUrl<TData = Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError = unknown>(
 provider: 'google' | 'github' | 'apple', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof socialAuthControllerGetSocialAuthUrl>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSocialAuthControllerGetSocialAuthUrlQueryOptions(provider,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * This endpoint is the redirect URI for the social provider. It exchanges the authorization code for user profile information, finds or creates a local user, and returns authentication tokens.
 * @summary Handle the callback from the social provider
 */
export type socialAuthControllerSocialAuthCallbackResponse200 = {
  data: AuthDto
  status: 200
}
    
export type socialAuthControllerSocialAuthCallbackResponseSuccess = (socialAuthControllerSocialAuthCallbackResponse200) & {
  headers: Headers;
};
;

export type socialAuthControllerSocialAuthCallbackResponse = (socialAuthControllerSocialAuthCallbackResponseSuccess)

export const getSocialAuthControllerSocialAuthCallbackUrl = (provider: 'google' | 'github' | 'apple',) => {


  

  return `/api/social/${provider}/callback`
}

export const socialAuthControllerSocialAuthCallback = async (provider: 'google' | 'github' | 'apple',
    socialCallbackDto: SocialCallbackDto, options?: RequestInit): Promise<socialAuthControllerSocialAuthCallbackResponse> => {
  
  return clientMutator<socialAuthControllerSocialAuthCallbackResponse>(getSocialAuthControllerSocialAuthCallbackUrl(provider),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      socialCallbackDto,)
  }
);}




export const getSocialAuthControllerSocialAuthCallbackMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialAuthControllerSocialAuthCallback>>, TError,{provider: 'google' | 'github' | 'apple';data: SocialCallbackDto}, TContext>, request?: SecondParameter<typeof clientMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof socialAuthControllerSocialAuthCallback>>, TError,{provider: 'google' | 'github' | 'apple';data: SocialCallbackDto}, TContext> => {

const mutationKey = ['socialAuthControllerSocialAuthCallback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof socialAuthControllerSocialAuthCallback>>, {provider: 'google' | 'github' | 'apple';data: SocialCallbackDto}> = (props) => {
          const {provider,data} = props ?? {};

          return  socialAuthControllerSocialAuthCallback(provider,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SocialAuthControllerSocialAuthCallbackMutationResult = NonNullable<Awaited<ReturnType<typeof socialAuthControllerSocialAuthCallback>>>
    export type SocialAuthControllerSocialAuthCallbackMutationBody = SocialCallbackDto
    export type SocialAuthControllerSocialAuthCallbackMutationError = unknown

    /**
 * @summary Handle the callback from the social provider
 */
export const useSocialAuthControllerSocialAuthCallback = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialAuthControllerSocialAuthCallback>>, TError,{provider: 'google' | 'github' | 'apple';data: SocialCallbackDto}, TContext>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof socialAuthControllerSocialAuthCallback>>,
        TError,
        {provider: 'google' | 'github' | 'apple';data: SocialCallbackDto},
        TContext
      > => {

      const mutationOptions = getSocialAuthControllerSocialAuthCallbackMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    