/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type {
  AuthControllerLogin200,
  AuthControllerRefresh200,
  AuthControllerRegister201,
  AuthControllerResetPassword200,
  AuthControllerResetPasswordBody,
  LoginDto,
  OkDto,
  RecoveryDto,
  RegisterDto,
  UpdatePasswordDto,
  UserSessionDto,
} from ".././schemas";

import { customInstance } from ".././mutator";

/**
 * @summary Register a new user
 */
export type authControllerRegisterResponse201 = {
  data: AuthControllerRegister201;
  status: 201;
};

export type authControllerRegisterResponseSuccess =
  authControllerRegisterResponse201 & {
    headers: Headers;
  };
export type authControllerRegisterResponse =
  authControllerRegisterResponseSuccess;

export const getAuthControllerRegisterUrl = () => {
  return `/auth/register`;
};

export const authControllerRegister = async (
  registerDto: RegisterDto,
  options?: RequestInit,
): Promise<authControllerRegisterResponse> => {
  return customInstance<authControllerRegisterResponse>(
    getAuthControllerRegisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(registerDto),
    },
  );
};

/**
 * @summary Log in a user
 */
export type authControllerLoginResponse200 = {
  data: AuthControllerLogin200;
  status: 200;
};

export type authControllerLoginResponseSuccess =
  authControllerLoginResponse200 & {
    headers: Headers;
  };
export type authControllerLoginResponse = authControllerLoginResponseSuccess;

export const getAuthControllerLoginUrl = () => {
  return `/auth/login`;
};

export const authControllerLogin = async (
  loginDto: LoginDto,
  options?: RequestInit,
): Promise<authControllerLoginResponse> => {
  return customInstance<authControllerLoginResponse>(
    getAuthControllerLoginUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(loginDto),
    },
  );
};

/**
 * @summary Refresh an access token
 */
export type authControllerRefreshResponse200 = {
  data: AuthControllerRefresh200;
  status: 200;
};

export type authControllerRefreshResponseSuccess =
  authControllerRefreshResponse200 & {
    headers: Headers;
  };
export type authControllerRefreshResponse =
  authControllerRefreshResponseSuccess;

export const getAuthControllerRefreshUrl = () => {
  return `/auth/refresh`;
};

export const authControllerRefresh = async (
  options?: RequestInit,
): Promise<authControllerRefreshResponse> => {
  return customInstance<authControllerRefreshResponse>(
    getAuthControllerRefreshUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Log out the current session
 */
export type authControllerLogoutResponse200 = {
  data: OkDto;
  status: 200;
};

export type authControllerLogoutResponseSuccess =
  authControllerLogoutResponse200 & {
    headers: Headers;
  };
export type authControllerLogoutResponse = authControllerLogoutResponseSuccess;

export const getAuthControllerLogoutUrl = () => {
  return `/auth/logout`;
};

export const authControllerLogout = async (
  options?: RequestInit,
): Promise<authControllerLogoutResponse> => {
  return customInstance<authControllerLogoutResponse>(
    getAuthControllerLogoutUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Initiate password recovery
 */
export type authControllerRecoveryResponse200 = {
  data: OkDto;
  status: 200;
};

export type authControllerRecoveryResponseSuccess =
  authControllerRecoveryResponse200 & {
    headers: Headers;
  };
export type authControllerRecoveryResponse =
  authControllerRecoveryResponseSuccess;

export const getAuthControllerRecoveryUrl = () => {
  return `/auth/recovery`;
};

export const authControllerRecovery = async (
  recoveryDto: RecoveryDto,
  options?: RequestInit,
): Promise<authControllerRecoveryResponse> => {
  return customInstance<authControllerRecoveryResponse>(
    getAuthControllerRecoveryUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(recoveryDto),
    },
  );
};

/**
 * @summary Reset password using a recovery token
 */
export type authControllerResetPasswordResponse200 = {
  data: AuthControllerResetPassword200;
  status: 200;
};

export type authControllerResetPasswordResponseSuccess =
  authControllerResetPasswordResponse200 & {
    headers: Headers;
  };
export type authControllerResetPasswordResponse =
  authControllerResetPasswordResponseSuccess;

export const getAuthControllerResetPasswordUrl = () => {
  return `/auth/reset-password`;
};

export const authControllerResetPassword = async (
  authControllerResetPasswordBody: AuthControllerResetPasswordBody,
  options?: RequestInit,
): Promise<authControllerResetPasswordResponse> => {
  return customInstance<authControllerResetPasswordResponse>(
    getAuthControllerResetPasswordUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(authControllerResetPasswordBody),
    },
  );
};

/**
 * @summary Change password for an authenticated user
 */
export type authControllerChangePasswordResponse200 = {
  data: OkDto;
  status: 200;
};

export type authControllerChangePasswordResponseSuccess =
  authControllerChangePasswordResponse200 & {
    headers: Headers;
  };
export type authControllerChangePasswordResponse =
  authControllerChangePasswordResponseSuccess;

export const getAuthControllerChangePasswordUrl = () => {
  return `/auth/change-password`;
};

export const authControllerChangePassword = async (
  updatePasswordDto: UpdatePasswordDto,
  options?: RequestInit,
): Promise<authControllerChangePasswordResponse> => {
  return customInstance<authControllerChangePasswordResponse>(
    getAuthControllerChangePasswordUrl(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updatePasswordDto),
    },
  );
};

/**
 * @summary Get the current user's active sessions
 */
export type authControllerGetSessionsResponse200 = {
  data: UserSessionDto[];
  status: 200;
};

export type authControllerGetSessionsResponseSuccess =
  authControllerGetSessionsResponse200 & {
    headers: Headers;
  };
export type authControllerGetSessionsResponse =
  authControllerGetSessionsResponseSuccess;

export const getAuthControllerGetSessionsUrl = () => {
  return `/auth/sessions`;
};

export const authControllerGetSessions = async (
  options?: RequestInit,
): Promise<authControllerGetSessionsResponse> => {
  return customInstance<authControllerGetSessionsResponse>(
    getAuthControllerGetSessionsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Log out all sessions for the current user
 */
export type authControllerDropAllSessionsResponse200 = {
  data: OkDto;
  status: 200;
};

export type authControllerDropAllSessionsResponseSuccess =
  authControllerDropAllSessionsResponse200 & {
    headers: Headers;
  };
export type authControllerDropAllSessionsResponse =
  authControllerDropAllSessionsResponseSuccess;

export const getAuthControllerDropAllSessionsUrl = () => {
  return `/auth/sessions`;
};

export const authControllerDropAllSessions = async (
  options?: RequestInit,
): Promise<authControllerDropAllSessionsResponse> => {
  return customInstance<authControllerDropAllSessionsResponse>(
    getAuthControllerDropAllSessionsUrl(),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Log out a specific session by its key
 */
export type authControllerDropSessionResponse200 = {
  data: OkDto;
  status: 200;
};

export type authControllerDropSessionResponseSuccess =
  authControllerDropSessionResponse200 & {
    headers: Headers;
  };
export type authControllerDropSessionResponse =
  authControllerDropSessionResponseSuccess;

export const getAuthControllerDropSessionUrl = (key: string) => {
  return `/auth/sessions/${key}`;
};

export const authControllerDropSession = async (
  key: string,
  options?: RequestInit,
): Promise<authControllerDropSessionResponse> => {
  return customInstance<authControllerDropSessionResponse>(
    getAuthControllerDropSessionUrl(key),
    {
      ...options,
      method: "DELETE",
    },
  );
};
