/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import * as zod from 'zod';

/**
 * @summary Verify OTP and get token
 */
export const otpControllerVerifyBodyCodeMin = 6;
export const otpControllerVerifyBodyCodeMax = 6;

export const otpControllerVerifyBody = zod.object({
  identifier: zod
    .string()
    .describe('The identifier for OTP (email, phone, userId, etc.)'),
  code: zod
    .string()
    .min(otpControllerVerifyBodyCodeMin)
    .max(otpControllerVerifyBodyCodeMax)
    .describe('6-character OTP code'),
  type: zod
    .enum(['invite', 'verify', 'recovery', 'discount', 'reset_password'])
    .describe('Type of OTP operation'),
});

export const otpControllerVerifyResponse = zod.object({
  token: zod.string().describe('The verified token'),
  message: zod.string().describe('Success message'),
});

/**
 * @summary Resend OTP for end user
 */
export const otpControllerResendForUserBody = zod.object({
  identifier: zod
    .string()
    .describe('The identifier for OTP (email, phone, userId, etc.)'),
  type: zod
    .enum(['invite', 'verify', 'recovery', 'discount', 'reset_password'])
    .describe('Type of OTP operation'),
});

export const otpControllerResendForUserResponse = zod.object({
  message: zod.string().describe('Success message'),
});
