/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  PostsQueryControllerFindAll200,
  PostsQueryControllerFindAllParams,
  PostsQueryControllerFindSitemap200,
  PostsQueryControllerFindSitemapParams
} from '../kodkafaApi.schemas';

import { clientMutator } from '../../../lib/api/client.mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get all posts with pagination
 */
export type postsQueryControllerFindAllResponse200 = {
  data: PostsQueryControllerFindAll200
  status: 200
}

export type postsQueryControllerFindAllResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type postsQueryControllerFindAllResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type postsQueryControllerFindAllResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type postsQueryControllerFindAllResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type postsQueryControllerFindAllResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type postsQueryControllerFindAllResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type postsQueryControllerFindAllResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type postsQueryControllerFindAllResponseSuccess = (postsQueryControllerFindAllResponse200) & {
  headers: Headers;
};
export type postsQueryControllerFindAllResponseError = (postsQueryControllerFindAllResponse400 | postsQueryControllerFindAllResponse401 | postsQueryControllerFindAllResponse403 | postsQueryControllerFindAllResponse404 | postsQueryControllerFindAllResponse409 | postsQueryControllerFindAllResponse422 | postsQueryControllerFindAllResponse500) & {
  headers: Headers;
};

export type postsQueryControllerFindAllResponse = (postsQueryControllerFindAllResponseSuccess | postsQueryControllerFindAllResponseError)

export const getPostsQueryControllerFindAllUrl = (params?: PostsQueryControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/posts?${stringifiedParams}` : `/api/posts`
}

export const postsQueryControllerFindAll = async (params?: PostsQueryControllerFindAllParams, options?: RequestInit): Promise<postsQueryControllerFindAllResponse> => {
  
  return clientMutator<postsQueryControllerFindAllResponse>(getPostsQueryControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPostsQueryControllerFindAllInfiniteQueryKey = (params?: PostsQueryControllerFindAllParams,) => {
    return [
    'infinite', `/api/posts`, ...(params ? [params]: [])
    ] as const;
    }

export const getPostsQueryControllerFindAllQueryKey = (params?: PostsQueryControllerFindAllParams,) => {
    return [
    `/api/posts`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPostsQueryControllerFindAllInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindAll>>>, TError = ErrorResponseDto>(params?: PostsQueryControllerFindAllParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsQueryControllerFindAllInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsQueryControllerFindAll>>> = ({ signal }) => postsQueryControllerFindAll(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 30000, gcTime: 300000, retry: 2, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsQueryControllerFindAllInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsQueryControllerFindAll>>>
export type PostsQueryControllerFindAllInfiniteQueryError = ErrorResponseDto


export function usePostsQueryControllerFindAllInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindAll>>>, TError = ErrorResponseDto>(
 params: undefined |  PostsQueryControllerFindAllParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsQueryControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof postsQueryControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsQueryControllerFindAllInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindAll>>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindAllParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsQueryControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof postsQueryControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsQueryControllerFindAllInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindAll>>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindAllParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all posts with pagination
 */

export function usePostsQueryControllerFindAllInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindAll>>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindAllParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsQueryControllerFindAllInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostsQueryControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError = ErrorResponseDto>(params?: PostsQueryControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsQueryControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsQueryControllerFindAll>>> = ({ signal }) => postsQueryControllerFindAll(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 30000, gcTime: 300000, retry: 2, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsQueryControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof postsQueryControllerFindAll>>>
export type PostsQueryControllerFindAllQueryError = ErrorResponseDto


export function usePostsQueryControllerFindAll<TData = Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError = ErrorResponseDto>(
 params: undefined |  PostsQueryControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsQueryControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof postsQueryControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsQueryControllerFindAll<TData = Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsQueryControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof postsQueryControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsQueryControllerFindAll<TData = Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all posts with pagination
 */

export function usePostsQueryControllerFindAll<TData = Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsQueryControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get published posts for sitemap generation
 */
export type postsQueryControllerFindSitemapResponse200 = {
  data: PostsQueryControllerFindSitemap200
  status: 200
}

export type postsQueryControllerFindSitemapResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type postsQueryControllerFindSitemapResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type postsQueryControllerFindSitemapResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type postsQueryControllerFindSitemapResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type postsQueryControllerFindSitemapResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type postsQueryControllerFindSitemapResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type postsQueryControllerFindSitemapResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type postsQueryControllerFindSitemapResponseSuccess = (postsQueryControllerFindSitemapResponse200) & {
  headers: Headers;
};
export type postsQueryControllerFindSitemapResponseError = (postsQueryControllerFindSitemapResponse400 | postsQueryControllerFindSitemapResponse401 | postsQueryControllerFindSitemapResponse403 | postsQueryControllerFindSitemapResponse404 | postsQueryControllerFindSitemapResponse409 | postsQueryControllerFindSitemapResponse422 | postsQueryControllerFindSitemapResponse500) & {
  headers: Headers;
};

export type postsQueryControllerFindSitemapResponse = (postsQueryControllerFindSitemapResponseSuccess | postsQueryControllerFindSitemapResponseError)

export const getPostsQueryControllerFindSitemapUrl = (params?: PostsQueryControllerFindSitemapParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/posts/sitemap?${stringifiedParams}` : `/api/posts/sitemap`
}

export const postsQueryControllerFindSitemap = async (params?: PostsQueryControllerFindSitemapParams, options?: RequestInit): Promise<postsQueryControllerFindSitemapResponse> => {
  
  return clientMutator<postsQueryControllerFindSitemapResponse>(getPostsQueryControllerFindSitemapUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPostsQueryControllerFindSitemapInfiniteQueryKey = (params?: PostsQueryControllerFindSitemapParams,) => {
    return [
    'infinite', `/api/posts/sitemap`, ...(params ? [params]: [])
    ] as const;
    }

export const getPostsQueryControllerFindSitemapQueryKey = (params?: PostsQueryControllerFindSitemapParams,) => {
    return [
    `/api/posts/sitemap`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPostsQueryControllerFindSitemapInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>>, TError = ErrorResponseDto>(params?: PostsQueryControllerFindSitemapParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsQueryControllerFindSitemapInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>> = ({ signal }) => postsQueryControllerFindSitemap(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 30000, gcTime: 300000, retry: 2, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsQueryControllerFindSitemapInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>>
export type PostsQueryControllerFindSitemapInfiniteQueryError = ErrorResponseDto


export function usePostsQueryControllerFindSitemapInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>>, TError = ErrorResponseDto>(
 params: undefined |  PostsQueryControllerFindSitemapParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>,
          TError,
          Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsQueryControllerFindSitemapInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindSitemapParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>,
          TError,
          Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsQueryControllerFindSitemapInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindSitemapParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get published posts for sitemap generation
 */

export function usePostsQueryControllerFindSitemapInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindSitemapParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsQueryControllerFindSitemapInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostsQueryControllerFindSitemapQueryOptions = <TData = Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError = ErrorResponseDto>(params?: PostsQueryControllerFindSitemapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsQueryControllerFindSitemapQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>> = ({ signal }) => postsQueryControllerFindSitemap(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 30000, gcTime: 300000, retry: 2, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsQueryControllerFindSitemapQueryResult = NonNullable<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>>
export type PostsQueryControllerFindSitemapQueryError = ErrorResponseDto


export function usePostsQueryControllerFindSitemap<TData = Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError = ErrorResponseDto>(
 params: undefined |  PostsQueryControllerFindSitemapParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>,
          TError,
          Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsQueryControllerFindSitemap<TData = Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindSitemapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>,
          TError,
          Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsQueryControllerFindSitemap<TData = Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindSitemapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get published posts for sitemap generation
 */

export function usePostsQueryControllerFindSitemap<TData = Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError = ErrorResponseDto>(
 params?: PostsQueryControllerFindSitemapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsQueryControllerFindSitemap>>, TError, TData>>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsQueryControllerFindSitemapQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




