/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { ObjectId } from "./objectId";
import type { AddMemberDtoRole } from "./addMemberDtoRole";

export interface AddMemberDto {
  /** User ID to add as a project member */
  userId: ObjectId;
  /** Role to assign to the member */
  role: AddMemberDtoRole;
  /** Specific permissions/scopes to assign to the member */
  permissions?: string[];
}
