/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { ApiKeyDtoType } from "./apiKeyDtoType";

export interface ApiKeyDto {
  /** Name of the API key */
  name: string;
  /** Client type (determines grant types and fields) */
  type: ApiKeyDtoType;
  /** Public client identifier */
  clientId: string;
  /**
   * Project ID this key belongs to
   * @minLength 24
   * @maxLength 24
   */
  projectId: string;
  /** Scopes assigned to this API key */
  scopes: string[];
  /** Allowed redirect URIs. Required for mobile; optional for confidential. */
  callbackUrls: string[];
  /** Description of the API key */
  description: string;
  /** Whether the API key is active */
  isActive: boolean;
  /** Keyset generation number for rotation */
  keysetGeneration?: number;
  /**
   * The unique id of the creator
   * @minLength 24
   * @maxLength 24
   */
  readonly createdBy: string;
  /**
   * The unique id
   * @minLength 24
   * @maxLength 24
   */
  readonly id: string;
}
