/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { AttestRequestDtoPlatform } from "./attestRequestDtoPlatform";

export interface AttestRequestDto {
  /** OAuth 2.0 Client ID (must be mobile type) */
  client_id: string;
  /** Platform identifier */
  platform: AttestRequestDtoPlatform;
  /**
   * Base64url-encoded nonce (minimum 128 bits)
   * @minLength 16
   */
  nonce: string;
  /** Platform-specific attestation token (iOS: App Attest, Android: Play Integrity) */
  attestation_token: string;
}
