/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export interface CategoryDto {
  /** The unique id */
  readonly id: string;
  /** Category slug */
  readonly slug: string;
  /** Category title */
  readonly title: string;
}
