/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { ObjectId } from "./objectId";

/**
 * Project ID (null for system templates)
 * @nullable
 */
export type CommunicationTemplateResponseDtoProjectId = ObjectId | null;
