/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

/**
 * Communication channel
 */
export type CommunicationTemplateResponseDtoChannel =
  (typeof CommunicationTemplateResponseDtoChannel)[keyof typeof CommunicationTemplateResponseDtoChannel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunicationTemplateResponseDtoChannel = {
  email: "email",
  sms: "sms",
  push: "push",
  webhook: "webhook",
  slack: "slack",
  discord: "discord",
  telegram: "telegram",
} as const;
