/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigurationResponseDtoCategory } from './configurationResponseDtoCategory';
import type { ConfigurationResponseDtoConfig } from './configurationResponseDtoConfig';

export interface ConfigurationResponseDto {
  /** Configuration ID */
  id: string;
  /** Configuration category */
  category: ConfigurationResponseDtoCategory;
  /** Configuration provider */
  provider: string;
  /** Configuration label (optional) */
  label?: string;
  /** Whether this configuration is active */
  isActive: boolean;
  /** Configuration data (provider-specific) */
  config: ConfigurationResponseDtoConfig;
  /** Provider display name */
  providerName: string;
  /** Provider description */
  providerDescription: string;
  /** Whether this configuration uses encryption */
  isEncrypted: boolean;
  /** Configuration creation date */
  createdAt: string;
  /** Configuration last update date */
  updatedAt: string;
}
