/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

/**
 * Communication channel
 */
export type CreateCommunicationTemplateDtoChannel = typeof CreateCommunicationTemplateDtoChannel[keyof typeof CreateCommunicationTemplateDtoChannel];


 
export const CreateCommunicationTemplateDtoChannel = {
  email: 'email',
  sms: 'sms',
  push: 'push',
  webhook: 'webhook',
  slack: 'slack',
  discord: 'discord',
  telegram: 'telegram',
} as const;
