/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { CreateCommunicationTemplateDtoPurpose } from "./createCommunicationTemplateDtoPurpose";
import type { CreateCommunicationTemplateDtoChannel } from "./createCommunicationTemplateDtoChannel";

export interface CreateCommunicationTemplateDto {
  /** Communication purpose */
  purpose: CreateCommunicationTemplateDtoPurpose;
  /** Communication channel */
  channel: CreateCommunicationTemplateDtoChannel;
  /** Template title */
  title: string;
  /** Rendered content (Handlebars template) */
  rendered: string;
  /** Plain text content (Handlebars template) */
  textTemplate: string;
  /** Template description */
  description?: string;
  /** Whether this template is active */
  isActive?: boolean;
}
