/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

/**
 * Client type (determines grant types and fields)
 */
export type CreateApiKeyDtoType =
  (typeof CreateApiKeyDtoType)[keyof typeof CreateApiKeyDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateApiKeyDtoType = {
  confidential: "confidential",
  mobile: "mobile",
} as const;
