/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { InvitationDtoStatus } from "./invitationDtoStatus";

export interface InvitationDto {
  /** Invitation ID (token) */
  invitationId: string;
  /** Email address of the invited user */
  email: string;
  /** Invitation status */
  status: InvitationDtoStatus;
  /** Invitation creation date */
  createdAt: string;
  /** Invitation expiration date */
  expiresAt: string;
  /** User ID who sent the invitation */
  invitedBy: string;
}
