/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export interface OAuthTokenResponseDto {
  /** The access token (JWT) */
  access_token: string;
  /** Token type (always "Bearer") */
  token_type: string;
  /** Token expiration time in seconds */
  expires_in: number;
  /** Refresh token (if applicable) */
  refresh_token?: string;
  /** Granted scopes (space-separated) */
  scope?: string;
}
