/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

/**
 * Hint about the type of token
 */
export type OAuthRevokeRequestDtoTokenTypeHint =
  (typeof OAuthRevokeRequestDtoTokenTypeHint)[keyof typeof OAuthRevokeRequestDtoTokenTypeHint];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OAuthRevokeRequestDtoTokenTypeHint = {
  access_token: "access_token",
  refresh_token: "refresh_token",
} as const;
