/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { OAuthIntrospectRequestDtoTokenTypeHint } from "./oAuthIntrospectRequestDtoTokenTypeHint";

export interface OAuthIntrospectRequestDto {
  /** The token to introspect */
  token: string;
  /** Hint about the type of token */
  token_type_hint?: OAuthIntrospectRequestDtoTokenTypeHint;
}
