/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { OAuthTokenRequestDtoGrantType } from './oAuthTokenRequestDtoGrantType';

export interface OAuthTokenRequestDto {
  /** OAuth 2.1 grant type */
  grant_type: OAuthTokenRequestDtoGrantType;
  /** Client ID (for all grant types) */
  client_id?: string;
  /** Client secret (confidential clients only, alternative to Basic Auth) */
  client_secret?: string;
  /** Authorization code (for authorization_code grant) */
  code?: string;
  /** PKCE code verifier (for authorization_code grant) */
  code_verifier?: string;
  /** Redirect URI (must match the one used in /authorize) */
  redirect_uri?: string;
  /** Refresh token (for refresh_token grant) */
  refresh_token?: string;
  /** Requested scopes (space-separated) */
  scope?: string;
}
