/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export interface OpenAIFileRefDto {
  /** The name of the file */
  name: string;
  /** A stable identifier for the file */
  id: string;
  /** The mime type of the file */
  mime_type: string;
  /** The URL to fetch the file which is valid for five minutes */
  download_link: string;
}
