/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export type PageMetaDtoOrder = typeof PageMetaDtoOrder[keyof typeof PageMetaDtoOrder];


 
export const PageMetaDtoOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
