/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { ObjectId } from "./objectId";
import type { PaginationDtoFilter } from "./paginationDtoFilter";

export interface PaginationDto {
  /** Cursor for the next page of results */
  cursor?: ObjectId;
  /** Number of items to load (max: 100) */
  limit?: number;
  sort?: string;
  filter?: PaginationDtoFilter;
  search?: string;
  status?: string;
}
