/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export interface PostSitemapDto {
  /** The unique id */
  readonly id: string;
  /** Domain label for multi-site support */
  domain: string;
  /** Post slug for URL construction */
  slug: string;
  /** Last modification date for sitemap lastmod */
  updatedAt: string;
}
