/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export type PostsControllerFindByTagsSort = typeof PostsControllerFindByTagsSort[keyof typeof PostsControllerFindByTagsSort];


 
export const PostsControllerFindByTagsSort = {
  title: 'title',
  slug: 'slug',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  '-title': '-title',
  '-slug': '-slug',
  '-createdAt': '-createdAt',
  '-updatedAt': '-updatedAt',
} as const;
