/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { PostsAnalyticsControllerGetPostStatistics200ByTypeItem } from "./postsAnalyticsControllerGetPostStatistics200ByTypeItem";
import type { PostsAnalyticsControllerGetPostStatistics200ByStatusItem } from "./postsAnalyticsControllerGetPostStatistics200ByStatusItem";

export type PostsAnalyticsControllerGetPostStatistics200 = {
  total?: number;
  published?: number;
  draft?: number;
  byType?: PostsAnalyticsControllerGetPostStatistics200ByTypeItem[];
  byStatus?: PostsAnalyticsControllerGetPostStatistics200ByStatusItem[];
};
