/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export type PostsControllerFindByStatusSort =
  (typeof PostsControllerFindByStatusSort)[keyof typeof PostsControllerFindByStatusSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsControllerFindByStatusSort = {
  title: "title",
  slug: "slug",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  "-title": "-title",
  "-slug": "-slug",
  "-createdAt": "-createdAt",
  "-updatedAt": "-updatedAt",
} as const;
