/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { ResendOtpDtoType } from './resendOtpDtoType';

export interface ResendOtpDto {
  /** The identifier for OTP (email, phone, userId, etc.) */
  identifier: string;
  /** Type of OTP operation */
  type: ResendOtpDtoType;
}
