/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export type UpdateProjectDtoScopesItem = typeof UpdateProjectDtoScopesItem[keyof typeof UpdateProjectDtoScopesItem];


 
export const UpdateProjectDtoScopesItem = {
  openid: 'openid',
  profile: 'profile',
  email: 'email',
  phone: 'phone',
  address: 'address',
  'basic:read': 'basic:read',
  'basic:write': 'basic:write',
  'project:read': 'project:read',
  'project:write': 'project:write',
  'project:delete': 'project:delete',
  'apikey:read': 'apikey:read',
  'apikey:write': 'apikey:write',
  'user:read': 'user:read',
  'user:write': 'user:write',
  'user:delete': 'user:delete',
  'session:read': 'session:read',
  'session:write': 'session:write',
  'note:read': 'note:read',
  'note:write': 'note:write',
  'note:delete': 'note:delete',
  'post:read': 'post:read',
  'post:write': 'post:write',
  'post:delete': 'post:delete',
  'files:read': 'files:read',
  'files:write': 'files:write',
  'files:delete': 'files:delete',
  'profile:read': 'profile:read',
  'profile:write': 'profile:write',
  'user:email:read': 'user:email:read',
  'user:phone:read': 'user:phone:read',
  'user:address:read': 'user:address:read',
  'user:profile:read': 'user:profile:read',
  'user:profile:write': 'user:profile:write',
  'account:read': 'account:read',
  'account:write': 'account:write',
  'auth:read': 'auth:read',
  'auth:write': 'auth:write',
  'user:read:all': 'user:read:all',
  'user:write:all': 'user:write:all',
  'user:delete:all': 'user:delete:all',
  'project:users:sessions:read': 'project:users:sessions:read',
  'project:users:sessions:delete': 'project:users:sessions:delete',
  'analytics:read': 'analytics:read',
  'settings:read': 'settings:read',
  'settings:write': 'settings:write',
  'webhooks:read': 'webhooks:read',
  'webhooks:write': 'webhooks:write',
  'configuration:read': 'configuration:read',
  'configuration:write': 'configuration:write',
  'configuration:delete': 'configuration:delete',
  'communication:read': 'communication:read',
  'communication:write': 'communication:write',
  'communication:delete': 'communication:delete',
} as const;
