/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { UpdatePostDtoType } from "./updatePostDtoType";
import type { UpdatePostDtoStatus } from "./updatePostDtoStatus";
import type { UpdateFileDto } from "./updateFileDto";

export interface UpdatePostDto {
  /**
   * Domain label for multi-site support (e.g., "main-website", "blog-subsite")
   * @maxLength 30
   */
  domain?: string;
  /**
   * @minLength 5
   * @maxLength 120
   */
  title?: string;
  /**
   * @minLength 5
   * @maxLength 120
   */
  slug?: string;
  /**
   * @minLength 10
   * @maxLength 500
   */
  description?: string;
  content?: string;
  tags?: string[];
  type?: UpdatePostDtoType;
  status?: UpdatePostDtoStatus;
  categories: string[];
  files?: UpdateFileDto[];
}
