/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export type UpdatePostDtoStatus =
  (typeof UpdatePostDtoStatus)[keyof typeof UpdatePostDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePostDtoStatus = {
  draft: "draft",
  hidden: "hidden",
  pending: "pending",
  scheduled: "scheduled",
  paused: "paused",
  active: "active",
  completed: "completed",
  published: "published",
  cancelled: "cancelled",
  expired: "expired",
  accepted: "accepted",
  rejected: "rejected",
} as const;
