/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { AuthorizeControllerAuthorizeResponseType } from './authorizeControllerAuthorizeResponseType';
import type { AuthorizeControllerAuthorizeCodeChallengeMethod } from './authorizeControllerAuthorizeCodeChallengeMethod';

export type AuthorizeControllerAuthorizeParams = {
/**
 * PAR request URI (RFC 9126)
 */
request_uri?: string;
/**
 * Response type (only "code" supported)
 */
response_type?: AuthorizeControllerAuthorizeResponseType;
/**
 * Client ID
 */
client_id?: string;
/**
 * Redirect URI (must be pre-registered)
 */
redirect_uri?: string;
/**
 * PKCE code challenge
 */
code_challenge?: string;
/**
 * PKCE code challenge method (only S256 supported)
 */
code_challenge_method?: AuthorizeControllerAuthorizeCodeChallengeMethod;
/**
 * State parameter for CSRF protection (mandatory for direct requests)
 */
state?: string;
/**
 * Requested scopes (space-separated)
 */
scope?: string;
};
