/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

/**
 * New role for the member
 */
export type ChangeMemberRoleDtoRole = typeof ChangeMemberRoleDtoRole[keyof typeof ChangeMemberRoleDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeMemberRoleDtoRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
  viewer: 'viewer',
} as const;
