/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

/**
 * Communication purpose
 */
export type CreateCommunicationTemplateDtoPurpose = typeof CreateCommunicationTemplateDtoPurpose[keyof typeof CreateCommunicationTemplateDtoPurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateCommunicationTemplateDtoPurpose = {
  invite: 'invite',
  verify: 'verify',
  recovery: 'recovery',
  discount: 'discount',
  reset_password: 'reset_password',
  welcome: 'welcome',
  notification: 'notification',
  alert: 'alert',
  reminder: 'reminder',
  promotion: 'promotion',
  newsletter: 'newsletter',
  announcement: 'announcement',
} as const;
