/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { Exif } from './exif';
import type { Point } from './point';

export interface PostFileDto {
  altText: string;
  exif?: Exif;
  location?: Point;
  src: string;
  type: string;
  /**
   * The unique id
   * @minLength 24
   * @maxLength 24
   */
  readonly id: string;
}
