/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import * as zod from 'zod';


/**
 * Returns server metadata including supported endpoints, grant types, and capabilities. Clients can use this for automatic configuration discovery.
 * @summary OAuth 2.0 Authorization Server Metadata (RFC 8414)
 */
export const discoveryControllerGetAuthorizationServerMetadataResponse = zod.object({
  "issuer": zod.string().optional(),
  "authorization_endpoint": zod.string().optional(),
  "token_endpoint": zod.string().optional(),
  "token_endpoint_auth_methods_supported": zod.array(zod.string()).optional(),
  "introspection_endpoint": zod.string().optional(),
  "introspection_endpoint_auth_methods_supported": zod.array(zod.string()).optional(),
  "revocation_endpoint": zod.string().optional(),
  "revocation_endpoint_auth_methods_supported": zod.array(zod.string()).optional(),
  "jwks_uri": zod.string().optional(),
  "response_types_supported": zod.array(zod.string()).optional(),
  "response_modes_supported": zod.array(zod.string()).optional(),
  "grant_types_supported": zod.array(zod.string()).optional(),
  "code_challenge_methods_supported": zod.array(zod.string()).optional(),
  "scopes_supported": zod.array(zod.string()).optional(),
  "service_documentation": zod.string().optional(),
  "ui_locales_supported": zod.array(zod.string()).optional()
})

/**
 * Returns public keys for JWT signature verification. Clients should cache keys and refresh on signature verification failure.
 * @summary JSON Web Key Set (RFC 7517)
 */
export const discoveryControllerGetJWKSResponse = zod.object({
  "keys": zod.array(zod.object({
  "kty": zod.string().optional(),
  "use": zod.string().optional(),
  "kid": zod.string().optional(),
  "alg": zod.string().optional(),
  "n": zod.string().optional(),
  "e": zod.string().optional()
})).optional()
})

