/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { CommunicationTemplateResponseDtoProjectId } from './communicationTemplateResponseDtoProjectId';
import type { CommunicationTemplateResponseDtoPurpose } from './communicationTemplateResponseDtoPurpose';
import type { CommunicationTemplateResponseDtoChannel } from './communicationTemplateResponseDtoChannel';

export interface CommunicationTemplateResponseDto {
  /** The unique id */
  id: string;
  /**
   * Project ID (null for system templates)
   * @nullable
   */
  projectId: CommunicationTemplateResponseDtoProjectId;
  /** Communication purpose */
  purpose: CommunicationTemplateResponseDtoPurpose;
  /** Communication channel */
  channel: CommunicationTemplateResponseDtoChannel;
  /** Template title */
  title: string;
  /** Rendered content (Handlebars template) */
  rendered: string;
  /** Plain text content (Handlebars template) */
  textTemplate: string;
  /** Template description */
  description?: string;
  /** Whether this template is active */
  isActive: boolean;
  /** User who created the template */
  createdBy: string;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}
