/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export type CreatePostDtoType =
  (typeof CreatePostDtoType)[keyof typeof CreatePostDtoType];

export const CreatePostDtoType = {
  category: 'category',
  post: 'post',
  article: 'article',
} as const;
