/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { Account } from './account';

export interface CreateUserDto {
  /**
   * The name of the User
   * @minLength 5
   * @maxLength 255
   */
  name?: string;
  /**
   * The password of the user.
   * @minLength 8
   * @maxLength 32
   */
  password?: string;
  /**
   * The username of the User
   * @minLength 4
   * @maxLength 31
   */
  username?: string;
  /**
   * The email of the User
   * @minLength 5
   * @maxLength 255
   */
  email?: string;
  /**
   * The phone of the user
   * @minLength 12
   * @maxLength 18
   */
  phone?: string;
  /**
   * Invitation code
   * @minLength 3
   * @maxLength 60
   */
  inviteCode?: string;
  /**
   * Project ID
   * @minLength 24
   * @maxLength 24
   */
  project: string;
  /** Determines user is verified or not. */
  isVerified: boolean;
  /** User accounts */
  accounts: Account[];
}
