/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export interface Exif {
  Model: string;
  Lens: string;
  ISOSpeedRatings: string;
  FocalLength: string;
  FNumber: string;
  ExposureTime: string;
  WhiteBalance: string;
  MeteringMode: string;
  DateTime: string;
  GPSLatitude: string;
  GPSLongitude: string;
}
