/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

/**
 * Platform (ios or android)
 */
export type OAuthAttestRequestDtoPlatform =
  (typeof OAuthAttestRequestDtoPlatform)[keyof typeof OAuthAttestRequestDtoPlatform];

export const OAuthAttestRequestDtoPlatform = {
  ios: 'ios',
  android: 'android',
} as const;
