/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export interface OAuthIntrospectResponseDto {
  /** Whether the token is currently active */
  active: boolean;
  /** Scopes associated with the token (space-separated) */
  scope?: string;
  /** Client ID */
  client_id?: string;
  /** Username (email or user ID) */
  username?: string;
  /** Token type */
  token_type?: string;
  /** Expiration timestamp (Unix time) */
  exp?: number;
  /** Issued at timestamp (Unix time) */
  iat?: number;
  /** Not before timestamp (Unix time) */
  nbf?: number;
  /** Subject (user ID) */
  sub?: string;
  /** Audience */
  aud?: string;
  /** Issuer */
  iss?: string;
  /** JWT ID */
  jti?: string;
}
