/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export interface PARResponseDto {
  /** Request URI to use in authorization endpoint */
  request_uri: string;
  /** Expiry time in seconds (typically 90 seconds) */
  expires_in: number;
}
