/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type { Account } from './account';

export interface UpdateUserDto {
  /**
   * Project ID this user belongs to
   * @minLength 24
   * @maxLength 24
   */
  projectId?: string;
  /**
   * The name of the User
   * @minLength 5
   * @maxLength 255
   */
  name?: string;
  accounts?: Account[];
  /**
   * The password of the user.
   * @minLength 8
   * @maxLength 32
   */
  password?: string;
  /** All scopes of the user. */
  scopes?: string[];
  /** Determines user is verified or not. */
  isVerified?: boolean;
  /** It corresponds user is active or not. */
  isDeactivated?: boolean;
  createdAt?: string;
  /**
   * The unique id
   * @minLength 24
   * @maxLength 24
   */
  readonly id?: string;
}
