/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */

export interface UpdatePasswordDto {
  /**
   * The password of the user.
   * @minLength 8
   * @maxLength 32
   */
  password: string;
  /**
   * The new password of the user.
   * @minLength 8
   * @maxLength 32
   */
  newPassword: string;
}
