/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  FileControllerUploadBody
} from '../kodkafaApi.schemas';

import { clientMutator } from '../../../lib/api/client.mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type fileControllerUploadResponse201 = {
  data: void
  status: 201
}
    
export type fileControllerUploadResponseSuccess = (fileControllerUploadResponse201) & {
  headers: Headers;
};
;

export type fileControllerUploadResponse = (fileControllerUploadResponseSuccess)

export const getFileControllerUploadUrl = () => {


  

  return `/api/file/upload`
}

export const fileControllerUpload = async (fileControllerUploadBody: FileControllerUploadBody, options?: RequestInit): Promise<fileControllerUploadResponse> => {
    const formData = new FormData();
if(fileControllerUploadBody.file !== undefined) {
 formData.append(`file`, fileControllerUploadBody.file)
 }

  return clientMutator<fileControllerUploadResponse>(getFileControllerUploadUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getFileControllerUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fileControllerUpload>>, TError,{data: FileControllerUploadBody}, TContext>, request?: SecondParameter<typeof clientMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof fileControllerUpload>>, TError,{data: FileControllerUploadBody}, TContext> => {

const mutationKey = ['fileControllerUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fileControllerUpload>>, {data: FileControllerUploadBody}> = (props) => {
          const {data} = props ?? {};

          return  fileControllerUpload(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FileControllerUploadMutationResult = NonNullable<Awaited<ReturnType<typeof fileControllerUpload>>>
    export type FileControllerUploadMutationBody = FileControllerUploadBody
    export type FileControllerUploadMutationError = unknown

    export const useFileControllerUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fileControllerUpload>>, TError,{data: FileControllerUploadBody}, TContext>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fileControllerUpload>>,
        TError,
        {data: FileControllerUploadBody},
        TContext
      > => {

      const mutationOptions = getFileControllerUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    