/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type {
  CreatePostDto,
  ErrorResponseDto,
  GptPostControllerSearchPostsParams,
  OpenAIFileUploadDto,
  PostDto,
  ResponseIdDto,
  ResponseStatusDto,
  UpdatePostDto,
  UpdatePostFileDto,
} from ".././schemas";

import { customInstance } from ".././mutator";

/**
 * @summary Create a GPT-generated post
 */
export type gptPostControllerCreateGptPostResponse201 = {
  data: ResponseIdDto;
  status: 201;
};

export type gptPostControllerCreateGptPostResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type gptPostControllerCreateGptPostResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type gptPostControllerCreateGptPostResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type gptPostControllerCreateGptPostResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type gptPostControllerCreateGptPostResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type gptPostControllerCreateGptPostResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type gptPostControllerCreateGptPostResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type gptPostControllerCreateGptPostResponseSuccess =
  gptPostControllerCreateGptPostResponse201 & {
    headers: Headers;
  };
export type gptPostControllerCreateGptPostResponseError = (
  | gptPostControllerCreateGptPostResponse400
  | gptPostControllerCreateGptPostResponse401
  | gptPostControllerCreateGptPostResponse403
  | gptPostControllerCreateGptPostResponse404
  | gptPostControllerCreateGptPostResponse409
  | gptPostControllerCreateGptPostResponse422
  | gptPostControllerCreateGptPostResponse500
) & {
  headers: Headers;
};

export type gptPostControllerCreateGptPostResponse =
  | gptPostControllerCreateGptPostResponseSuccess
  | gptPostControllerCreateGptPostResponseError;

export const getGptPostControllerCreateGptPostUrl = () => {
  return `/gpt/posts`;
};

export const gptPostControllerCreateGptPost = async (
  createPostDto: CreatePostDto,
  options?: RequestInit,
): Promise<gptPostControllerCreateGptPostResponse> => {
  return customInstance<gptPostControllerCreateGptPostResponse>(
    getGptPostControllerCreateGptPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createPostDto),
    },
  );
};

/**
 * @summary Search posts for GPT context
 */
export type gptPostControllerSearchPostsResponse200 = {
  data: PostDto[];
  status: 200;
};

export type gptPostControllerSearchPostsResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type gptPostControllerSearchPostsResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type gptPostControllerSearchPostsResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type gptPostControllerSearchPostsResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type gptPostControllerSearchPostsResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type gptPostControllerSearchPostsResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type gptPostControllerSearchPostsResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type gptPostControllerSearchPostsResponseSuccess =
  gptPostControllerSearchPostsResponse200 & {
    headers: Headers;
  };
export type gptPostControllerSearchPostsResponseError = (
  | gptPostControllerSearchPostsResponse400
  | gptPostControllerSearchPostsResponse401
  | gptPostControllerSearchPostsResponse403
  | gptPostControllerSearchPostsResponse404
  | gptPostControllerSearchPostsResponse409
  | gptPostControllerSearchPostsResponse422
  | gptPostControllerSearchPostsResponse500
) & {
  headers: Headers;
};

export type gptPostControllerSearchPostsResponse =
  | gptPostControllerSearchPostsResponseSuccess
  | gptPostControllerSearchPostsResponseError;

export const getGptPostControllerSearchPostsUrl = (
  params: GptPostControllerSearchPostsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/gpt/posts/search?${stringifiedParams}`
    : `/gpt/posts/search`;
};

export const gptPostControllerSearchPosts = async (
  params: GptPostControllerSearchPostsParams,
  options?: RequestInit,
): Promise<gptPostControllerSearchPostsResponse> => {
  return customInstance<gptPostControllerSearchPostsResponse>(
    getGptPostControllerSearchPostsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get post by ID for GPT processing
 */
export type gptPostControllerFindPostByIdResponse200 = {
  data: PostDto;
  status: 200;
};

export type gptPostControllerFindPostByIdResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type gptPostControllerFindPostByIdResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type gptPostControllerFindPostByIdResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type gptPostControllerFindPostByIdResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type gptPostControllerFindPostByIdResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type gptPostControllerFindPostByIdResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type gptPostControllerFindPostByIdResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type gptPostControllerFindPostByIdResponseSuccess =
  gptPostControllerFindPostByIdResponse200 & {
    headers: Headers;
  };
export type gptPostControllerFindPostByIdResponseError = (
  | gptPostControllerFindPostByIdResponse400
  | gptPostControllerFindPostByIdResponse401
  | gptPostControllerFindPostByIdResponse403
  | gptPostControllerFindPostByIdResponse404
  | gptPostControllerFindPostByIdResponse409
  | gptPostControllerFindPostByIdResponse422
  | gptPostControllerFindPostByIdResponse500
) & {
  headers: Headers;
};

export type gptPostControllerFindPostByIdResponse =
  | gptPostControllerFindPostByIdResponseSuccess
  | gptPostControllerFindPostByIdResponseError;

export const getGptPostControllerFindPostByIdUrl = (id: string) => {
  return `/gpt/posts/${id}`;
};

export const gptPostControllerFindPostById = async (
  id: string,
  options?: RequestInit,
): Promise<gptPostControllerFindPostByIdResponse> => {
  return customInstance<gptPostControllerFindPostByIdResponse>(
    getGptPostControllerFindPostByIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update post with GPT-generated content
 */
export type gptPostControllerUpdateGptPostResponse200 = {
  data: ResponseIdDto;
  status: 200;
};

export type gptPostControllerUpdateGptPostResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type gptPostControllerUpdateGptPostResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type gptPostControllerUpdateGptPostResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type gptPostControllerUpdateGptPostResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type gptPostControllerUpdateGptPostResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type gptPostControllerUpdateGptPostResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type gptPostControllerUpdateGptPostResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type gptPostControllerUpdateGptPostResponseSuccess =
  gptPostControllerUpdateGptPostResponse200 & {
    headers: Headers;
  };
export type gptPostControllerUpdateGptPostResponseError = (
  | gptPostControllerUpdateGptPostResponse400
  | gptPostControllerUpdateGptPostResponse401
  | gptPostControllerUpdateGptPostResponse403
  | gptPostControllerUpdateGptPostResponse404
  | gptPostControllerUpdateGptPostResponse409
  | gptPostControllerUpdateGptPostResponse422
  | gptPostControllerUpdateGptPostResponse500
) & {
  headers: Headers;
};

export type gptPostControllerUpdateGptPostResponse =
  | gptPostControllerUpdateGptPostResponseSuccess
  | gptPostControllerUpdateGptPostResponseError;

export const getGptPostControllerUpdateGptPostUrl = (id: string) => {
  return `/gpt/posts/${id}`;
};

export const gptPostControllerUpdateGptPost = async (
  id: string,
  updatePostDto: UpdatePostDto,
  options?: RequestInit,
): Promise<gptPostControllerUpdateGptPostResponse> => {
  return customInstance<gptPostControllerUpdateGptPostResponse>(
    getGptPostControllerUpdateGptPostUrl(id),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updatePostDto),
    },
  );
};

/**
 * Process and attach files from OpenAI Assistant API responses
 * @summary Upload files from OpenAI file references
 */
export type gptPostControllerUploadOpenAIFilesResponse200 = {
  data: ResponseStatusDto;
  status: 200;
};

export type gptPostControllerUploadOpenAIFilesResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type gptPostControllerUploadOpenAIFilesResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type gptPostControllerUploadOpenAIFilesResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type gptPostControllerUploadOpenAIFilesResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type gptPostControllerUploadOpenAIFilesResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type gptPostControllerUploadOpenAIFilesResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type gptPostControllerUploadOpenAIFilesResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type gptPostControllerUploadOpenAIFilesResponseSuccess =
  gptPostControllerUploadOpenAIFilesResponse200 & {
    headers: Headers;
  };
export type gptPostControllerUploadOpenAIFilesResponseError = (
  | gptPostControllerUploadOpenAIFilesResponse400
  | gptPostControllerUploadOpenAIFilesResponse401
  | gptPostControllerUploadOpenAIFilesResponse403
  | gptPostControllerUploadOpenAIFilesResponse404
  | gptPostControllerUploadOpenAIFilesResponse409
  | gptPostControllerUploadOpenAIFilesResponse422
  | gptPostControllerUploadOpenAIFilesResponse500
) & {
  headers: Headers;
};

export type gptPostControllerUploadOpenAIFilesResponse =
  | gptPostControllerUploadOpenAIFilesResponseSuccess
  | gptPostControllerUploadOpenAIFilesResponseError;

export const getGptPostControllerUploadOpenAIFilesUrl = (id: string) => {
  return `/gpt/posts/${id}/openai-files`;
};

export const gptPostControllerUploadOpenAIFiles = async (
  id: string,
  openAIFileUploadDto: OpenAIFileUploadDto,
  options?: RequestInit,
): Promise<gptPostControllerUploadOpenAIFilesResponse> => {
  return customInstance<gptPostControllerUploadOpenAIFilesResponse>(
    getGptPostControllerUploadOpenAIFilesUrl(id),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(openAIFileUploadDto),
    },
  );
};

/**
 * @summary Update file metadata for GPT-uploaded files
 */
export type gptPostControllerUpdatePostFileResponse200 = {
  data: ResponseIdDto;
  status: 200;
};

export type gptPostControllerUpdatePostFileResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type gptPostControllerUpdatePostFileResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type gptPostControllerUpdatePostFileResponse403 = {
  data: ErrorResponseDto;
  status: 403;
};

export type gptPostControllerUpdatePostFileResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type gptPostControllerUpdatePostFileResponse409 = {
  data: ErrorResponseDto;
  status: 409;
};

export type gptPostControllerUpdatePostFileResponse422 = {
  data: ErrorResponseDto;
  status: 422;
};

export type gptPostControllerUpdatePostFileResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type gptPostControllerUpdatePostFileResponseSuccess =
  gptPostControllerUpdatePostFileResponse200 & {
    headers: Headers;
  };
export type gptPostControllerUpdatePostFileResponseError = (
  | gptPostControllerUpdatePostFileResponse400
  | gptPostControllerUpdatePostFileResponse401
  | gptPostControllerUpdatePostFileResponse403
  | gptPostControllerUpdatePostFileResponse404
  | gptPostControllerUpdatePostFileResponse409
  | gptPostControllerUpdatePostFileResponse422
  | gptPostControllerUpdatePostFileResponse500
) & {
  headers: Headers;
};

export type gptPostControllerUpdatePostFileResponse =
  | gptPostControllerUpdatePostFileResponseSuccess
  | gptPostControllerUpdatePostFileResponseError;

export const getGptPostControllerUpdatePostFileUrl = (
  id: string,
  fileId: string,
) => {
  return `/gpt/posts/${id}/files/${fileId}`;
};

export const gptPostControllerUpdatePostFile = async (
  id: string,
  fileId: string,
  updatePostFileDto: UpdatePostFileDto,
  options?: RequestInit,
): Promise<gptPostControllerUpdatePostFileResponse> => {
  return customInstance<gptPostControllerUpdatePostFileResponse>(
    getGptPostControllerUpdatePostFileUrl(id, fileId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updatePostFileDto),
    },
  );
};
