/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import * as zod from 'zod';

/**
 * @summary Create a new post
 */
export const postsControllerCreateBodyDomainMax = 30;

export const postsControllerCreateBodyTitleMin = 5;
export const postsControllerCreateBodyTitleMax = 120;

export const postsControllerCreateBodySlugMin = 5;
export const postsControllerCreateBodySlugMax = 120;

export const postsControllerCreateBodyDescriptionMin = 10;
export const postsControllerCreateBodyDescriptionMax = 500;

export const postsControllerCreateBody = zod.object({
  domain: zod
    .string()
    .max(postsControllerCreateBodyDomainMax)
    .describe(
      'Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'
    ),
  categories: zod.array(zod.string()),
  title: zod
    .string()
    .min(postsControllerCreateBodyTitleMin)
    .max(postsControllerCreateBodyTitleMax),
  slug: zod
    .string()
    .min(postsControllerCreateBodySlugMin)
    .max(postsControllerCreateBodySlugMax),
  description: zod
    .string()
    .min(postsControllerCreateBodyDescriptionMin)
    .max(postsControllerCreateBodyDescriptionMax)
    .optional(),
  tags: zod.array(zod.string()).optional(),
  type: zod.enum(['category', 'post', 'article']).optional(),
  status: zod
    .enum([
      'draft',
      'hidden',
      'pending',
      'scheduled',
      'paused',
      'active',
      'completed',
      'published',
      'cancelled',
      'expired',
      'accepted',
      'rejected',
    ])
    .optional(),
});

/**
 * @summary Get post by ID
 */
export const postsControllerFindOnePathIdMin = 24;
export const postsControllerFindOnePathIdMax = 24;

export const postsControllerFindOneParams = zod.object({
  id: zod
    .string()
    .min(postsControllerFindOnePathIdMin)
    .max(postsControllerFindOnePathIdMax)
    .describe('MongoDB ObjectId'),
});

export const postsControllerFindOneResponseProjectIdMin = 24;
export const postsControllerFindOneResponseProjectIdMax = 24;

export const postsControllerFindOneResponseDomainMax = 30;

export const postsControllerFindOneResponseTitleMin = 5;
export const postsControllerFindOneResponseTitleMax = 120;

export const postsControllerFindOneResponseSlugMin = 5;
export const postsControllerFindOneResponseSlugMax = 120;

export const postsControllerFindOneResponseDescriptionMin = 10;
export const postsControllerFindOneResponseDescriptionMax = 500;

export const postsControllerFindOneResponseIdMin = 24;
export const postsControllerFindOneResponseIdMax = 24;

export const postsControllerFindOneResponseAuthorIdMin = 24;
export const postsControllerFindOneResponseAuthorIdMax = 24;

export const postsControllerFindOneResponseFilesItemLocationTypeDefault =
  'Point';
export const postsControllerFindOneResponseFilesItemIdMin = 24;
export const postsControllerFindOneResponseFilesItemIdMax = 24;

export const postsControllerFindOneResponseAuthorIdMinOne = 24;
export const postsControllerFindOneResponseAuthorIdMaxOne = 24;

export const postsControllerFindOneResponse = zod.object({
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  projectId: zod
    .string()
    .min(postsControllerFindOneResponseProjectIdMin)
    .max(postsControllerFindOneResponseProjectIdMax)
    .describe('The unique id'),
  domain: zod
    .string()
    .max(postsControllerFindOneResponseDomainMax)
    .describe(
      'Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'
    ),
  title: zod
    .string()
    .min(postsControllerFindOneResponseTitleMin)
    .max(postsControllerFindOneResponseTitleMax),
  slug: zod
    .string()
    .min(postsControllerFindOneResponseSlugMin)
    .max(postsControllerFindOneResponseSlugMax),
  description: zod
    .string()
    .min(postsControllerFindOneResponseDescriptionMin)
    .max(postsControllerFindOneResponseDescriptionMax)
    .optional(),
  content: zod.string().optional(),
  tags: zod.array(zod.string()).optional(),
  type: zod.enum(['category', 'post', 'article']).optional(),
  status: zod
    .enum([
      'draft',
      'hidden',
      'pending',
      'scheduled',
      'paused',
      'active',
      'completed',
      'published',
      'cancelled',
      'expired',
      'accepted',
      'rejected',
    ])
    .optional(),
  id: zod
    .string()
    .min(postsControllerFindOneResponseIdMin)
    .max(postsControllerFindOneResponseIdMax)
    .describe('The unique id'),
  authorId: zod
    .string()
    .min(postsControllerFindOneResponseAuthorIdMin)
    .max(postsControllerFindOneResponseAuthorIdMax)
    .describe('The unique id of the author'),
  files: zod
    .array(
      zod.object({
        altText: zod.string(),
        exif: zod
          .object({
            Model: zod.string(),
            Lens: zod.string(),
            ISOSpeedRatings: zod.string(),
            FocalLength: zod.string(),
            FNumber: zod.string(),
            ExposureTime: zod.string(),
            WhiteBalance: zod.string(),
            MeteringMode: zod.string(),
            DateTime: zod.string(),
            GPSLatitude: zod.string(),
            GPSLongitude: zod.string(),
          })
          .optional(),
        location: zod
          .object({
            type: zod.string(),
            coordinates: zod.array(zod.number()),
          })
          .optional(),
        src: zod.string(),
        type: zod.string(),
        id: zod
          .string()
          .min(postsControllerFindOneResponseFilesItemIdMin)
          .max(postsControllerFindOneResponseFilesItemIdMax)
          .describe('The unique id'),
      })
    )
    .optional()
    .describe('Post files (origin field excluded)'),
  author: zod
    .object({
      id: zod
        .string()
        .min(postsControllerFindOneResponseAuthorIdMinOne)
        .max(postsControllerFindOneResponseAuthorIdMaxOne)
        .describe('The unique id of the author'),
      name: zod.string().describe('Author name'),
      username: zod
        .string()
        .optional()
        .describe(
          'Author username (falls back to userId if username not found)'
        ),
    })
    .optional()
    .describe('Post author information (populated)'),
  categories: zod
    .array(
      zod.object({
        id: zod.string().describe('The unique id'),
        slug: zod.string().describe('Category slug'),
        title: zod.string().describe('Category title'),
      })
    )
    .optional()
    .describe('Post categories (populated)'),
});

/**
 * @summary Update post by ID
 */
export const postsControllerUpdatePathIdMin = 24;
export const postsControllerUpdatePathIdMax = 24;

export const postsControllerUpdateParams = zod.object({
  id: zod
    .string()
    .min(postsControllerUpdatePathIdMin)
    .max(postsControllerUpdatePathIdMax)
    .describe('MongoDB ObjectId'),
});

export const postsControllerUpdateBodyDomainMax = 30;

export const postsControllerUpdateBodyTitleMin = 5;
export const postsControllerUpdateBodyTitleMax = 120;

export const postsControllerUpdateBodySlugMin = 5;
export const postsControllerUpdateBodySlugMax = 120;

export const postsControllerUpdateBodyDescriptionMin = 10;
export const postsControllerUpdateBodyDescriptionMax = 500;

export const postsControllerUpdateBodyFilesItemLocationTypeDefault = 'Point';
export const postsControllerUpdateBodyFilesItemIdMin = 24;
export const postsControllerUpdateBodyFilesItemIdMax = 24;

export const postsControllerUpdateBody = zod.object({
  domain: zod
    .string()
    .max(postsControllerUpdateBodyDomainMax)
    .optional()
    .describe(
      'Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'
    ),
  title: zod
    .string()
    .min(postsControllerUpdateBodyTitleMin)
    .max(postsControllerUpdateBodyTitleMax)
    .optional(),
  slug: zod
    .string()
    .min(postsControllerUpdateBodySlugMin)
    .max(postsControllerUpdateBodySlugMax)
    .optional(),
  description: zod
    .string()
    .min(postsControllerUpdateBodyDescriptionMin)
    .max(postsControllerUpdateBodyDescriptionMax)
    .optional(),
  content: zod.string().optional(),
  tags: zod.array(zod.string()).optional(),
  type: zod.enum(['category', 'post', 'article']).optional(),
  status: zod
    .enum([
      'draft',
      'hidden',
      'pending',
      'scheduled',
      'paused',
      'active',
      'completed',
      'published',
      'cancelled',
      'expired',
      'accepted',
      'rejected',
    ])
    .optional(),
  categories: zod.array(zod.string()),
  files: zod
    .array(
      zod.object({
        altText: zod.string(),
        location: zod
          .object({
            type: zod.string(),
            coordinates: zod.array(zod.number()),
          })
          .optional(),
        id: zod
          .string()
          .min(postsControllerUpdateBodyFilesItemIdMin)
          .max(postsControllerUpdateBodyFilesItemIdMax)
          .describe('The unique id'),
      })
    )
    .optional(),
});

export const postsControllerUpdateResponse = zod.object({
  id: zod.string().describe('Response id as string'),
});

/**
 * @summary Delete post by ID
 */
export const postsControllerDeletePathIdMin = 24;
export const postsControllerDeletePathIdMax = 24;

export const postsControllerDeleteParams = zod.object({
  id: zod
    .string()
    .min(postsControllerDeletePathIdMin)
    .max(postsControllerDeletePathIdMax)
    .describe('MongoDB ObjectId'),
});

export const postsControllerDeleteResponse = zod.object({
  id: zod.string().describe('Response id as string'),
});

/**
 * @summary Get post by slug and domain
 */
export const postsControllerFindOneBySlugParams = zod.object({
  slug: zod.string(),
  domain: zod.string(),
});

export const postsControllerFindOneBySlugResponseProjectIdMin = 24;
export const postsControllerFindOneBySlugResponseProjectIdMax = 24;

export const postsControllerFindOneBySlugResponseDomainMax = 30;

export const postsControllerFindOneBySlugResponseTitleMin = 5;
export const postsControllerFindOneBySlugResponseTitleMax = 120;

export const postsControllerFindOneBySlugResponseSlugMin = 5;
export const postsControllerFindOneBySlugResponseSlugMax = 120;

export const postsControllerFindOneBySlugResponseDescriptionMin = 10;
export const postsControllerFindOneBySlugResponseDescriptionMax = 500;

export const postsControllerFindOneBySlugResponseIdMin = 24;
export const postsControllerFindOneBySlugResponseIdMax = 24;

export const postsControllerFindOneBySlugResponseAuthorIdMin = 24;
export const postsControllerFindOneBySlugResponseAuthorIdMax = 24;

export const postsControllerFindOneBySlugResponseFilesItemLocationTypeDefault =
  'Point';
export const postsControllerFindOneBySlugResponseFilesItemIdMin = 24;
export const postsControllerFindOneBySlugResponseFilesItemIdMax = 24;

export const postsControllerFindOneBySlugResponseAuthorIdMinOne = 24;
export const postsControllerFindOneBySlugResponseAuthorIdMaxOne = 24;

export const postsControllerFindOneBySlugResponse = zod.object({
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  projectId: zod
    .string()
    .min(postsControllerFindOneBySlugResponseProjectIdMin)
    .max(postsControllerFindOneBySlugResponseProjectIdMax)
    .describe('The unique id'),
  domain: zod
    .string()
    .max(postsControllerFindOneBySlugResponseDomainMax)
    .describe(
      'Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'
    ),
  title: zod
    .string()
    .min(postsControllerFindOneBySlugResponseTitleMin)
    .max(postsControllerFindOneBySlugResponseTitleMax),
  slug: zod
    .string()
    .min(postsControllerFindOneBySlugResponseSlugMin)
    .max(postsControllerFindOneBySlugResponseSlugMax),
  description: zod
    .string()
    .min(postsControllerFindOneBySlugResponseDescriptionMin)
    .max(postsControllerFindOneBySlugResponseDescriptionMax)
    .optional(),
  content: zod.string().optional(),
  tags: zod.array(zod.string()).optional(),
  type: zod.enum(['category', 'post', 'article']).optional(),
  status: zod
    .enum([
      'draft',
      'hidden',
      'pending',
      'scheduled',
      'paused',
      'active',
      'completed',
      'published',
      'cancelled',
      'expired',
      'accepted',
      'rejected',
    ])
    .optional(),
  id: zod
    .string()
    .min(postsControllerFindOneBySlugResponseIdMin)
    .max(postsControllerFindOneBySlugResponseIdMax)
    .describe('The unique id'),
  authorId: zod
    .string()
    .min(postsControllerFindOneBySlugResponseAuthorIdMin)
    .max(postsControllerFindOneBySlugResponseAuthorIdMax)
    .describe('The unique id of the author'),
  files: zod
    .array(
      zod.object({
        altText: zod.string(),
        exif: zod
          .object({
            Model: zod.string(),
            Lens: zod.string(),
            ISOSpeedRatings: zod.string(),
            FocalLength: zod.string(),
            FNumber: zod.string(),
            ExposureTime: zod.string(),
            WhiteBalance: zod.string(),
            MeteringMode: zod.string(),
            DateTime: zod.string(),
            GPSLatitude: zod.string(),
            GPSLongitude: zod.string(),
          })
          .optional(),
        location: zod
          .object({
            type: zod.string(),
            coordinates: zod.array(zod.number()),
          })
          .optional(),
        src: zod.string(),
        type: zod.string(),
        id: zod
          .string()
          .min(postsControllerFindOneBySlugResponseFilesItemIdMin)
          .max(postsControllerFindOneBySlugResponseFilesItemIdMax)
          .describe('The unique id'),
      })
    )
    .optional()
    .describe('Post files (origin field excluded)'),
  author: zod
    .object({
      id: zod
        .string()
        .min(postsControllerFindOneBySlugResponseAuthorIdMinOne)
        .max(postsControllerFindOneBySlugResponseAuthorIdMaxOne)
        .describe('The unique id of the author'),
      name: zod.string().describe('Author name'),
      username: zod
        .string()
        .optional()
        .describe(
          'Author username (falls back to userId if username not found)'
        ),
    })
    .optional()
    .describe('Post author information (populated)'),
  categories: zod
    .array(
      zod.object({
        id: zod.string().describe('The unique id'),
        slug: zod.string().describe('Category slug'),
        title: zod.string().describe('Category title'),
      })
    )
    .optional()
    .describe('Post categories (populated)'),
});

/**
 * @summary Get posts by domain with keyset pagination
 */
export const postsControllerFindByDomainParams = zod.object({
  domain: zod.string(),
});

export const postsControllerFindByDomainQueryParams = zod.object({
  limit: zod
    .number()
    .optional()
    .describe('Number of items to return (1-100, default: 20)'),
  after: zod
    .string()
    .optional()
    .describe('Cursor token for next page (forward pagination)'),
  before: zod
    .string()
    .optional()
    .describe('Cursor token for previous page (backward pagination)'),
  sort: zod
    .enum([
      'title',
      'slug',
      'createdAt',
      'updatedAt',
      '-title',
      '-slug',
      '-createdAt',
      '-updatedAt',
    ])
    .optional()
    .describe(
      "Sort field with optional '-' prefix for descending. Allowed fields: title, slug, createdAt, updatedAt"
    ),
  projectId: zod.string().optional().describe('Filter by projectId'),
  domain: zod.string().optional().describe('Filter by domain (exact match)'),
  'domain.contains': zod
    .string()
    .optional()
    .describe('Filter where domain contains the value (case-sensitive)'),
  'domain.icontains': zod
    .string()
    .optional()
    .describe('Filter where domain contains the value (case-insensitive)'),
  'domain.startsWith': zod
    .string()
    .optional()
    .describe('Filter where domain starts with the value (case-sensitive)'),
  'domain.istartswith': zod
    .string()
    .optional()
    .describe('Filter where domain starts with the value (case-insensitive)'),
  title: zod.string().optional().describe('Filter by title (exact match)'),
  'title.contains': zod
    .string()
    .optional()
    .describe('Filter where title contains the value (case-sensitive)'),
  'title.icontains': zod
    .string()
    .optional()
    .describe('Filter where title contains the value (case-insensitive)'),
  'title.startsWith': zod
    .string()
    .optional()
    .describe('Filter where title starts with the value (case-sensitive)'),
  'title.istartswith': zod
    .string()
    .optional()
    .describe('Filter where title starts with the value (case-insensitive)'),
  slug: zod.string().optional().describe('Filter by slug (exact match)'),
  'slug.contains': zod
    .string()
    .optional()
    .describe('Filter where slug contains the value (case-sensitive)'),
  'slug.icontains': zod
    .string()
    .optional()
    .describe('Filter where slug contains the value (case-insensitive)'),
  'slug.startsWith': zod
    .string()
    .optional()
    .describe('Filter where slug starts with the value (case-sensitive)'),
  'slug.istartswith': zod
    .string()
    .optional()
    .describe('Filter where slug starts with the value (case-insensitive)'),
  description: zod
    .string()
    .optional()
    .describe('Filter by description (exact match)'),
  'description.contains': zod
    .string()
    .optional()
    .describe('Filter where description contains the value (case-sensitive)'),
  'description.icontains': zod
    .string()
    .optional()
    .describe('Filter where description contains the value (case-insensitive)'),
  'description.startsWith': zod
    .string()
    .optional()
    .describe(
      'Filter where description starts with the value (case-sensitive)'
    ),
  'description.istartswith': zod
    .string()
    .optional()
    .describe(
      'Filter where description starts with the value (case-insensitive)'
    ),
  tags: zod.string().optional().describe('Filter by tags (exact match)'),
  'tags.contains': zod
    .string()
    .optional()
    .describe('Filter where tags contains the value (case-sensitive)'),
  'tags.icontains': zod
    .string()
    .optional()
    .describe('Filter where tags contains the value (case-insensitive)'),
  'tags.startsWith': zod
    .string()
    .optional()
    .describe('Filter where tags starts with the value (case-sensitive)'),
  'tags.istartswith': zod
    .string()
    .optional()
    .describe('Filter where tags starts with the value (case-insensitive)'),
  type: zod.string().optional().describe('Filter by type (exact match)'),
  'type.contains': zod
    .string()
    .optional()
    .describe('Filter where type contains the value (case-sensitive)'),
  'type.icontains': zod
    .string()
    .optional()
    .describe('Filter where type contains the value (case-insensitive)'),
  'type.startsWith': zod
    .string()
    .optional()
    .describe('Filter where type starts with the value (case-sensitive)'),
  'type.istartswith': zod
    .string()
    .optional()
    .describe('Filter where type starts with the value (case-insensitive)'),
  status: zod.string().optional().describe('Filter by status (exact match)'),
  'status.contains': zod
    .string()
    .optional()
    .describe('Filter where status contains the value (case-sensitive)'),
  'status.icontains': zod
    .string()
    .optional()
    .describe('Filter where status contains the value (case-insensitive)'),
  'status.startsWith': zod
    .string()
    .optional()
    .describe('Filter where status starts with the value (case-sensitive)'),
  'status.istartswith': zod
    .string()
    .optional()
    .describe('Filter where status starts with the value (case-insensitive)'),
  authorId: zod.string().optional().describe('Filter by authorId'),
  categories: zod.string().optional().describe('Filter by categories'),
  createdAt: zod
    .string()
    .optional()
    .describe('Filter by createdAt (exact match, ISO date string for dates)'),
  'createdAt.gt': zod
    .string()
    .optional()
    .describe('Filter where createdAt is greater than'),
  'createdAt.gte': zod
    .string()
    .optional()
    .describe('Filter where createdAt is greater than or equal'),
  'createdAt.lt': zod
    .string()
    .optional()
    .describe('Filter where createdAt is less than'),
  'createdAt.lte': zod
    .string()
    .optional()
    .describe('Filter where createdAt is less than or equal'),
  updatedAt: zod
    .string()
    .optional()
    .describe('Filter by updatedAt (exact match, ISO date string for dates)'),
  'updatedAt.gt': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is greater than'),
  'updatedAt.gte': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is greater than or equal'),
  'updatedAt.lt': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is less than'),
  'updatedAt.lte': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is less than or equal'),
});

export const postsControllerFindByDomainResponseItemsItemProjectIdMin = 24;
export const postsControllerFindByDomainResponseItemsItemProjectIdMax = 24;

export const postsControllerFindByDomainResponseItemsItemDomainMax = 30;

export const postsControllerFindByDomainResponseItemsItemTitleMin = 5;
export const postsControllerFindByDomainResponseItemsItemTitleMax = 120;

export const postsControllerFindByDomainResponseItemsItemSlugMin = 5;
export const postsControllerFindByDomainResponseItemsItemSlugMax = 120;

export const postsControllerFindByDomainResponseItemsItemDescriptionMin = 10;
export const postsControllerFindByDomainResponseItemsItemDescriptionMax = 500;

export const postsControllerFindByDomainResponseItemsItemIdMin = 24;
export const postsControllerFindByDomainResponseItemsItemIdMax = 24;

export const postsControllerFindByDomainResponseItemsItemAuthorIdMin = 24;
export const postsControllerFindByDomainResponseItemsItemAuthorIdMax = 24;

export const postsControllerFindByDomainResponseItemsItemFilesItemLocationTypeDefault =
  'Point';
export const postsControllerFindByDomainResponseItemsItemFilesItemIdMin = 24;
export const postsControllerFindByDomainResponseItemsItemFilesItemIdMax = 24;

export const postsControllerFindByDomainResponseItemsItemAuthorIdMinOne = 24;
export const postsControllerFindByDomainResponseItemsItemAuthorIdMaxOne = 24;

export const postsControllerFindByDomainResponse = zod.object({
  items: zod
    .array(
      zod.object({
        createdAt: zod.string().datetime({}),
        updatedAt: zod.string().datetime({}),
        projectId: zod
          .string()
          .min(postsControllerFindByDomainResponseItemsItemProjectIdMin)
          .max(postsControllerFindByDomainResponseItemsItemProjectIdMax)
          .describe('The unique id'),
        domain: zod
          .string()
          .max(postsControllerFindByDomainResponseItemsItemDomainMax)
          .describe(
            'Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'
          ),
        title: zod
          .string()
          .min(postsControllerFindByDomainResponseItemsItemTitleMin)
          .max(postsControllerFindByDomainResponseItemsItemTitleMax),
        slug: zod
          .string()
          .min(postsControllerFindByDomainResponseItemsItemSlugMin)
          .max(postsControllerFindByDomainResponseItemsItemSlugMax),
        description: zod
          .string()
          .min(postsControllerFindByDomainResponseItemsItemDescriptionMin)
          .max(postsControllerFindByDomainResponseItemsItemDescriptionMax)
          .optional(),
        content: zod.string().optional(),
        tags: zod.array(zod.string()).optional(),
        type: zod.enum(['category', 'post', 'article']).optional(),
        status: zod
          .enum([
            'draft',
            'hidden',
            'pending',
            'scheduled',
            'paused',
            'active',
            'completed',
            'published',
            'cancelled',
            'expired',
            'accepted',
            'rejected',
          ])
          .optional(),
        id: zod
          .string()
          .min(postsControllerFindByDomainResponseItemsItemIdMin)
          .max(postsControllerFindByDomainResponseItemsItemIdMax)
          .describe('The unique id'),
        authorId: zod
          .string()
          .min(postsControllerFindByDomainResponseItemsItemAuthorIdMin)
          .max(postsControllerFindByDomainResponseItemsItemAuthorIdMax)
          .describe('The unique id of the author'),
        files: zod
          .array(
            zod.object({
              altText: zod.string(),
              exif: zod
                .object({
                  Model: zod.string(),
                  Lens: zod.string(),
                  ISOSpeedRatings: zod.string(),
                  FocalLength: zod.string(),
                  FNumber: zod.string(),
                  ExposureTime: zod.string(),
                  WhiteBalance: zod.string(),
                  MeteringMode: zod.string(),
                  DateTime: zod.string(),
                  GPSLatitude: zod.string(),
                  GPSLongitude: zod.string(),
                })
                .optional(),
              location: zod
                .object({
                  type: zod.string(),
                  coordinates: zod.array(zod.number()),
                })
                .optional(),
              src: zod.string(),
              type: zod.string(),
              id: zod
                .string()
                .min(postsControllerFindByDomainResponseItemsItemFilesItemIdMin)
                .max(postsControllerFindByDomainResponseItemsItemFilesItemIdMax)
                .describe('The unique id'),
            })
          )
          .optional()
          .describe('Post files (origin field excluded)'),
        author: zod
          .object({
            id: zod
              .string()
              .min(postsControllerFindByDomainResponseItemsItemAuthorIdMinOne)
              .max(postsControllerFindByDomainResponseItemsItemAuthorIdMaxOne)
              .describe('The unique id of the author'),
            name: zod.string().describe('Author name'),
            username: zod
              .string()
              .optional()
              .describe(
                'Author username (falls back to userId if username not found)'
              ),
          })
          .optional()
          .describe('Post author information (populated)'),
        categories: zod
          .array(
            zod.object({
              id: zod.string().describe('The unique id'),
              slug: zod.string().describe('Category slug'),
              title: zod.string().describe('Category title'),
            })
          )
          .optional()
          .describe('Post categories (populated)'),
      })
    )
    .optional(),
  meta: zod
    .object({
      nextCursor: zod.string().optional(),
      prevCursor: zod.string().optional(),
      hasNextPage: zod.boolean(),
      hasPrevPage: zod.boolean(),
      limit: zod.number(),
      sort: zod.string(),
      order: zod.enum(['asc', 'desc']),
    })
    .optional(),
});

/**
 * @summary Get posts by status with keyset pagination
 */
export const postsControllerFindByStatusParams = zod.object({
  status: zod.string(),
});

export const postsControllerFindByStatusQueryParams = zod.object({
  limit: zod
    .number()
    .optional()
    .describe('Number of items to return (1-100, default: 20)'),
  after: zod
    .string()
    .optional()
    .describe('Cursor token for next page (forward pagination)'),
  before: zod
    .string()
    .optional()
    .describe('Cursor token for previous page (backward pagination)'),
  sort: zod
    .enum([
      'title',
      'slug',
      'createdAt',
      'updatedAt',
      '-title',
      '-slug',
      '-createdAt',
      '-updatedAt',
    ])
    .optional()
    .describe(
      "Sort field with optional '-' prefix for descending. Allowed fields: title, slug, createdAt, updatedAt"
    ),
  projectId: zod.string().optional().describe('Filter by projectId'),
  domain: zod.string().optional().describe('Filter by domain (exact match)'),
  'domain.contains': zod
    .string()
    .optional()
    .describe('Filter where domain contains the value (case-sensitive)'),
  'domain.icontains': zod
    .string()
    .optional()
    .describe('Filter where domain contains the value (case-insensitive)'),
  'domain.startsWith': zod
    .string()
    .optional()
    .describe('Filter where domain starts with the value (case-sensitive)'),
  'domain.istartswith': zod
    .string()
    .optional()
    .describe('Filter where domain starts with the value (case-insensitive)'),
  title: zod.string().optional().describe('Filter by title (exact match)'),
  'title.contains': zod
    .string()
    .optional()
    .describe('Filter where title contains the value (case-sensitive)'),
  'title.icontains': zod
    .string()
    .optional()
    .describe('Filter where title contains the value (case-insensitive)'),
  'title.startsWith': zod
    .string()
    .optional()
    .describe('Filter where title starts with the value (case-sensitive)'),
  'title.istartswith': zod
    .string()
    .optional()
    .describe('Filter where title starts with the value (case-insensitive)'),
  slug: zod.string().optional().describe('Filter by slug (exact match)'),
  'slug.contains': zod
    .string()
    .optional()
    .describe('Filter where slug contains the value (case-sensitive)'),
  'slug.icontains': zod
    .string()
    .optional()
    .describe('Filter where slug contains the value (case-insensitive)'),
  'slug.startsWith': zod
    .string()
    .optional()
    .describe('Filter where slug starts with the value (case-sensitive)'),
  'slug.istartswith': zod
    .string()
    .optional()
    .describe('Filter where slug starts with the value (case-insensitive)'),
  description: zod
    .string()
    .optional()
    .describe('Filter by description (exact match)'),
  'description.contains': zod
    .string()
    .optional()
    .describe('Filter where description contains the value (case-sensitive)'),
  'description.icontains': zod
    .string()
    .optional()
    .describe('Filter where description contains the value (case-insensitive)'),
  'description.startsWith': zod
    .string()
    .optional()
    .describe(
      'Filter where description starts with the value (case-sensitive)'
    ),
  'description.istartswith': zod
    .string()
    .optional()
    .describe(
      'Filter where description starts with the value (case-insensitive)'
    ),
  tags: zod.string().optional().describe('Filter by tags (exact match)'),
  'tags.contains': zod
    .string()
    .optional()
    .describe('Filter where tags contains the value (case-sensitive)'),
  'tags.icontains': zod
    .string()
    .optional()
    .describe('Filter where tags contains the value (case-insensitive)'),
  'tags.startsWith': zod
    .string()
    .optional()
    .describe('Filter where tags starts with the value (case-sensitive)'),
  'tags.istartswith': zod
    .string()
    .optional()
    .describe('Filter where tags starts with the value (case-insensitive)'),
  type: zod.string().optional().describe('Filter by type (exact match)'),
  'type.contains': zod
    .string()
    .optional()
    .describe('Filter where type contains the value (case-sensitive)'),
  'type.icontains': zod
    .string()
    .optional()
    .describe('Filter where type contains the value (case-insensitive)'),
  'type.startsWith': zod
    .string()
    .optional()
    .describe('Filter where type starts with the value (case-sensitive)'),
  'type.istartswith': zod
    .string()
    .optional()
    .describe('Filter where type starts with the value (case-insensitive)'),
  status: zod.string().optional().describe('Filter by status (exact match)'),
  'status.contains': zod
    .string()
    .optional()
    .describe('Filter where status contains the value (case-sensitive)'),
  'status.icontains': zod
    .string()
    .optional()
    .describe('Filter where status contains the value (case-insensitive)'),
  'status.startsWith': zod
    .string()
    .optional()
    .describe('Filter where status starts with the value (case-sensitive)'),
  'status.istartswith': zod
    .string()
    .optional()
    .describe('Filter where status starts with the value (case-insensitive)'),
  authorId: zod.string().optional().describe('Filter by authorId'),
  categories: zod.string().optional().describe('Filter by categories'),
  createdAt: zod
    .string()
    .optional()
    .describe('Filter by createdAt (exact match, ISO date string for dates)'),
  'createdAt.gt': zod
    .string()
    .optional()
    .describe('Filter where createdAt is greater than'),
  'createdAt.gte': zod
    .string()
    .optional()
    .describe('Filter where createdAt is greater than or equal'),
  'createdAt.lt': zod
    .string()
    .optional()
    .describe('Filter where createdAt is less than'),
  'createdAt.lte': zod
    .string()
    .optional()
    .describe('Filter where createdAt is less than or equal'),
  updatedAt: zod
    .string()
    .optional()
    .describe('Filter by updatedAt (exact match, ISO date string for dates)'),
  'updatedAt.gt': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is greater than'),
  'updatedAt.gte': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is greater than or equal'),
  'updatedAt.lt': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is less than'),
  'updatedAt.lte': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is less than or equal'),
});

export const postsControllerFindByStatusResponseItemsItemProjectIdMin = 24;
export const postsControllerFindByStatusResponseItemsItemProjectIdMax = 24;

export const postsControllerFindByStatusResponseItemsItemDomainMax = 30;

export const postsControllerFindByStatusResponseItemsItemTitleMin = 5;
export const postsControllerFindByStatusResponseItemsItemTitleMax = 120;

export const postsControllerFindByStatusResponseItemsItemSlugMin = 5;
export const postsControllerFindByStatusResponseItemsItemSlugMax = 120;

export const postsControllerFindByStatusResponseItemsItemDescriptionMin = 10;
export const postsControllerFindByStatusResponseItemsItemDescriptionMax = 500;

export const postsControllerFindByStatusResponseItemsItemIdMin = 24;
export const postsControllerFindByStatusResponseItemsItemIdMax = 24;

export const postsControllerFindByStatusResponseItemsItemAuthorIdMin = 24;
export const postsControllerFindByStatusResponseItemsItemAuthorIdMax = 24;

export const postsControllerFindByStatusResponseItemsItemFilesItemLocationTypeDefault =
  'Point';
export const postsControllerFindByStatusResponseItemsItemFilesItemIdMin = 24;
export const postsControllerFindByStatusResponseItemsItemFilesItemIdMax = 24;

export const postsControllerFindByStatusResponseItemsItemAuthorIdMinOne = 24;
export const postsControllerFindByStatusResponseItemsItemAuthorIdMaxOne = 24;

export const postsControllerFindByStatusResponse = zod.object({
  items: zod
    .array(
      zod.object({
        createdAt: zod.string().datetime({}),
        updatedAt: zod.string().datetime({}),
        projectId: zod
          .string()
          .min(postsControllerFindByStatusResponseItemsItemProjectIdMin)
          .max(postsControllerFindByStatusResponseItemsItemProjectIdMax)
          .describe('The unique id'),
        domain: zod
          .string()
          .max(postsControllerFindByStatusResponseItemsItemDomainMax)
          .describe(
            'Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'
          ),
        title: zod
          .string()
          .min(postsControllerFindByStatusResponseItemsItemTitleMin)
          .max(postsControllerFindByStatusResponseItemsItemTitleMax),
        slug: zod
          .string()
          .min(postsControllerFindByStatusResponseItemsItemSlugMin)
          .max(postsControllerFindByStatusResponseItemsItemSlugMax),
        description: zod
          .string()
          .min(postsControllerFindByStatusResponseItemsItemDescriptionMin)
          .max(postsControllerFindByStatusResponseItemsItemDescriptionMax)
          .optional(),
        content: zod.string().optional(),
        tags: zod.array(zod.string()).optional(),
        type: zod.enum(['category', 'post', 'article']).optional(),
        status: zod
          .enum([
            'draft',
            'hidden',
            'pending',
            'scheduled',
            'paused',
            'active',
            'completed',
            'published',
            'cancelled',
            'expired',
            'accepted',
            'rejected',
          ])
          .optional(),
        id: zod
          .string()
          .min(postsControllerFindByStatusResponseItemsItemIdMin)
          .max(postsControllerFindByStatusResponseItemsItemIdMax)
          .describe('The unique id'),
        authorId: zod
          .string()
          .min(postsControllerFindByStatusResponseItemsItemAuthorIdMin)
          .max(postsControllerFindByStatusResponseItemsItemAuthorIdMax)
          .describe('The unique id of the author'),
        files: zod
          .array(
            zod.object({
              altText: zod.string(),
              exif: zod
                .object({
                  Model: zod.string(),
                  Lens: zod.string(),
                  ISOSpeedRatings: zod.string(),
                  FocalLength: zod.string(),
                  FNumber: zod.string(),
                  ExposureTime: zod.string(),
                  WhiteBalance: zod.string(),
                  MeteringMode: zod.string(),
                  DateTime: zod.string(),
                  GPSLatitude: zod.string(),
                  GPSLongitude: zod.string(),
                })
                .optional(),
              location: zod
                .object({
                  type: zod.string(),
                  coordinates: zod.array(zod.number()),
                })
                .optional(),
              src: zod.string(),
              type: zod.string(),
              id: zod
                .string()
                .min(postsControllerFindByStatusResponseItemsItemFilesItemIdMin)
                .max(postsControllerFindByStatusResponseItemsItemFilesItemIdMax)
                .describe('The unique id'),
            })
          )
          .optional()
          .describe('Post files (origin field excluded)'),
        author: zod
          .object({
            id: zod
              .string()
              .min(postsControllerFindByStatusResponseItemsItemAuthorIdMinOne)
              .max(postsControllerFindByStatusResponseItemsItemAuthorIdMaxOne)
              .describe('The unique id of the author'),
            name: zod.string().describe('Author name'),
            username: zod
              .string()
              .optional()
              .describe(
                'Author username (falls back to userId if username not found)'
              ),
          })
          .optional()
          .describe('Post author information (populated)'),
        categories: zod
          .array(
            zod.object({
              id: zod.string().describe('The unique id'),
              slug: zod.string().describe('Category slug'),
              title: zod.string().describe('Category title'),
            })
          )
          .optional()
          .describe('Post categories (populated)'),
      })
    )
    .optional(),
  meta: zod
    .object({
      nextCursor: zod.string().optional(),
      prevCursor: zod.string().optional(),
      hasNextPage: zod.boolean(),
      hasPrevPage: zod.boolean(),
      limit: zod.number(),
      sort: zod.string(),
      order: zod.enum(['asc', 'desc']),
    })
    .optional(),
});

/**
 * @summary Get posts by tags with keyset pagination
 */
export const postsControllerFindByTagsQueryParams = zod.object({
  limit: zod
    .number()
    .optional()
    .describe('Number of items to return (1-100, default: 20)'),
  after: zod
    .string()
    .optional()
    .describe('Cursor token for next page (forward pagination)'),
  before: zod
    .string()
    .optional()
    .describe('Cursor token for previous page (backward pagination)'),
  sort: zod
    .enum([
      'title',
      'slug',
      'createdAt',
      'updatedAt',
      '-title',
      '-slug',
      '-createdAt',
      '-updatedAt',
    ])
    .optional()
    .describe(
      "Sort field with optional '-' prefix for descending. Allowed fields: title, slug, createdAt, updatedAt"
    ),
  projectId: zod.string().optional().describe('Filter by projectId'),
  domain: zod.string().optional().describe('Filter by domain (exact match)'),
  'domain.contains': zod
    .string()
    .optional()
    .describe('Filter where domain contains the value (case-sensitive)'),
  'domain.icontains': zod
    .string()
    .optional()
    .describe('Filter where domain contains the value (case-insensitive)'),
  'domain.startsWith': zod
    .string()
    .optional()
    .describe('Filter where domain starts with the value (case-sensitive)'),
  'domain.istartswith': zod
    .string()
    .optional()
    .describe('Filter where domain starts with the value (case-insensitive)'),
  title: zod.string().optional().describe('Filter by title (exact match)'),
  'title.contains': zod
    .string()
    .optional()
    .describe('Filter where title contains the value (case-sensitive)'),
  'title.icontains': zod
    .string()
    .optional()
    .describe('Filter where title contains the value (case-insensitive)'),
  'title.startsWith': zod
    .string()
    .optional()
    .describe('Filter where title starts with the value (case-sensitive)'),
  'title.istartswith': zod
    .string()
    .optional()
    .describe('Filter where title starts with the value (case-insensitive)'),
  slug: zod.string().optional().describe('Filter by slug (exact match)'),
  'slug.contains': zod
    .string()
    .optional()
    .describe('Filter where slug contains the value (case-sensitive)'),
  'slug.icontains': zod
    .string()
    .optional()
    .describe('Filter where slug contains the value (case-insensitive)'),
  'slug.startsWith': zod
    .string()
    .optional()
    .describe('Filter where slug starts with the value (case-sensitive)'),
  'slug.istartswith': zod
    .string()
    .optional()
    .describe('Filter where slug starts with the value (case-insensitive)'),
  description: zod
    .string()
    .optional()
    .describe('Filter by description (exact match)'),
  'description.contains': zod
    .string()
    .optional()
    .describe('Filter where description contains the value (case-sensitive)'),
  'description.icontains': zod
    .string()
    .optional()
    .describe('Filter where description contains the value (case-insensitive)'),
  'description.startsWith': zod
    .string()
    .optional()
    .describe(
      'Filter where description starts with the value (case-sensitive)'
    ),
  'description.istartswith': zod
    .string()
    .optional()
    .describe(
      'Filter where description starts with the value (case-insensitive)'
    ),
  tags: zod.string().optional().describe('Filter by tags (exact match)'),
  'tags.contains': zod
    .string()
    .optional()
    .describe('Filter where tags contains the value (case-sensitive)'),
  'tags.icontains': zod
    .string()
    .optional()
    .describe('Filter where tags contains the value (case-insensitive)'),
  'tags.startsWith': zod
    .string()
    .optional()
    .describe('Filter where tags starts with the value (case-sensitive)'),
  'tags.istartswith': zod
    .string()
    .optional()
    .describe('Filter where tags starts with the value (case-insensitive)'),
  type: zod.string().optional().describe('Filter by type (exact match)'),
  'type.contains': zod
    .string()
    .optional()
    .describe('Filter where type contains the value (case-sensitive)'),
  'type.icontains': zod
    .string()
    .optional()
    .describe('Filter where type contains the value (case-insensitive)'),
  'type.startsWith': zod
    .string()
    .optional()
    .describe('Filter where type starts with the value (case-sensitive)'),
  'type.istartswith': zod
    .string()
    .optional()
    .describe('Filter where type starts with the value (case-insensitive)'),
  status: zod.string().optional().describe('Filter by status (exact match)'),
  'status.contains': zod
    .string()
    .optional()
    .describe('Filter where status contains the value (case-sensitive)'),
  'status.icontains': zod
    .string()
    .optional()
    .describe('Filter where status contains the value (case-insensitive)'),
  'status.startsWith': zod
    .string()
    .optional()
    .describe('Filter where status starts with the value (case-sensitive)'),
  'status.istartswith': zod
    .string()
    .optional()
    .describe('Filter where status starts with the value (case-insensitive)'),
  authorId: zod.string().optional().describe('Filter by authorId'),
  categories: zod.string().optional().describe('Filter by categories'),
  createdAt: zod
    .string()
    .optional()
    .describe('Filter by createdAt (exact match, ISO date string for dates)'),
  'createdAt.gt': zod
    .string()
    .optional()
    .describe('Filter where createdAt is greater than'),
  'createdAt.gte': zod
    .string()
    .optional()
    .describe('Filter where createdAt is greater than or equal'),
  'createdAt.lt': zod
    .string()
    .optional()
    .describe('Filter where createdAt is less than'),
  'createdAt.lte': zod
    .string()
    .optional()
    .describe('Filter where createdAt is less than or equal'),
  updatedAt: zod
    .string()
    .optional()
    .describe('Filter by updatedAt (exact match, ISO date string for dates)'),
  'updatedAt.gt': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is greater than'),
  'updatedAt.gte': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is greater than or equal'),
  'updatedAt.lt': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is less than'),
  'updatedAt.lte': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is less than or equal'),
});

export const postsControllerFindByTagsResponseItemsItemProjectIdMin = 24;
export const postsControllerFindByTagsResponseItemsItemProjectIdMax = 24;

export const postsControllerFindByTagsResponseItemsItemDomainMax = 30;

export const postsControllerFindByTagsResponseItemsItemTitleMin = 5;
export const postsControllerFindByTagsResponseItemsItemTitleMax = 120;

export const postsControllerFindByTagsResponseItemsItemSlugMin = 5;
export const postsControllerFindByTagsResponseItemsItemSlugMax = 120;

export const postsControllerFindByTagsResponseItemsItemDescriptionMin = 10;
export const postsControllerFindByTagsResponseItemsItemDescriptionMax = 500;

export const postsControllerFindByTagsResponseItemsItemIdMin = 24;
export const postsControllerFindByTagsResponseItemsItemIdMax = 24;

export const postsControllerFindByTagsResponseItemsItemAuthorIdMin = 24;
export const postsControllerFindByTagsResponseItemsItemAuthorIdMax = 24;

export const postsControllerFindByTagsResponseItemsItemFilesItemLocationTypeDefault =
  'Point';
export const postsControllerFindByTagsResponseItemsItemFilesItemIdMin = 24;
export const postsControllerFindByTagsResponseItemsItemFilesItemIdMax = 24;

export const postsControllerFindByTagsResponseItemsItemAuthorIdMinOne = 24;
export const postsControllerFindByTagsResponseItemsItemAuthorIdMaxOne = 24;

export const postsControllerFindByTagsResponse = zod.object({
  items: zod
    .array(
      zod.object({
        createdAt: zod.string().datetime({}),
        updatedAt: zod.string().datetime({}),
        projectId: zod
          .string()
          .min(postsControllerFindByTagsResponseItemsItemProjectIdMin)
          .max(postsControllerFindByTagsResponseItemsItemProjectIdMax)
          .describe('The unique id'),
        domain: zod
          .string()
          .max(postsControllerFindByTagsResponseItemsItemDomainMax)
          .describe(
            'Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'
          ),
        title: zod
          .string()
          .min(postsControllerFindByTagsResponseItemsItemTitleMin)
          .max(postsControllerFindByTagsResponseItemsItemTitleMax),
        slug: zod
          .string()
          .min(postsControllerFindByTagsResponseItemsItemSlugMin)
          .max(postsControllerFindByTagsResponseItemsItemSlugMax),
        description: zod
          .string()
          .min(postsControllerFindByTagsResponseItemsItemDescriptionMin)
          .max(postsControllerFindByTagsResponseItemsItemDescriptionMax)
          .optional(),
        content: zod.string().optional(),
        tags: zod.array(zod.string()).optional(),
        type: zod.enum(['category', 'post', 'article']).optional(),
        status: zod
          .enum([
            'draft',
            'hidden',
            'pending',
            'scheduled',
            'paused',
            'active',
            'completed',
            'published',
            'cancelled',
            'expired',
            'accepted',
            'rejected',
          ])
          .optional(),
        id: zod
          .string()
          .min(postsControllerFindByTagsResponseItemsItemIdMin)
          .max(postsControllerFindByTagsResponseItemsItemIdMax)
          .describe('The unique id'),
        authorId: zod
          .string()
          .min(postsControllerFindByTagsResponseItemsItemAuthorIdMin)
          .max(postsControllerFindByTagsResponseItemsItemAuthorIdMax)
          .describe('The unique id of the author'),
        files: zod
          .array(
            zod.object({
              altText: zod.string(),
              exif: zod
                .object({
                  Model: zod.string(),
                  Lens: zod.string(),
                  ISOSpeedRatings: zod.string(),
                  FocalLength: zod.string(),
                  FNumber: zod.string(),
                  ExposureTime: zod.string(),
                  WhiteBalance: zod.string(),
                  MeteringMode: zod.string(),
                  DateTime: zod.string(),
                  GPSLatitude: zod.string(),
                  GPSLongitude: zod.string(),
                })
                .optional(),
              location: zod
                .object({
                  type: zod.string(),
                  coordinates: zod.array(zod.number()),
                })
                .optional(),
              src: zod.string(),
              type: zod.string(),
              id: zod
                .string()
                .min(postsControllerFindByTagsResponseItemsItemFilesItemIdMin)
                .max(postsControllerFindByTagsResponseItemsItemFilesItemIdMax)
                .describe('The unique id'),
            })
          )
          .optional()
          .describe('Post files (origin field excluded)'),
        author: zod
          .object({
            id: zod
              .string()
              .min(postsControllerFindByTagsResponseItemsItemAuthorIdMinOne)
              .max(postsControllerFindByTagsResponseItemsItemAuthorIdMaxOne)
              .describe('The unique id of the author'),
            name: zod.string().describe('Author name'),
            username: zod
              .string()
              .optional()
              .describe(
                'Author username (falls back to userId if username not found)'
              ),
          })
          .optional()
          .describe('Post author information (populated)'),
        categories: zod
          .array(
            zod.object({
              id: zod.string().describe('The unique id'),
              slug: zod.string().describe('Category slug'),
              title: zod.string().describe('Category title'),
            })
          )
          .optional()
          .describe('Post categories (populated)'),
      })
    )
    .optional(),
  meta: zod
    .object({
      nextCursor: zod.string().optional(),
      prevCursor: zod.string().optional(),
      hasNextPage: zod.boolean(),
      hasPrevPage: zod.boolean(),
      limit: zod.number(),
      sort: zod.string(),
      order: zod.enum(['asc', 'desc']),
    })
    .optional(),
});

/**
 * @summary Get posts by author with keyset pagination
 */
export const postsControllerFindByAuthorPathIdMin = 24;
export const postsControllerFindByAuthorPathIdMax = 24;

export const postsControllerFindByAuthorParams = zod.object({
  id: zod
    .string()
    .min(postsControllerFindByAuthorPathIdMin)
    .max(postsControllerFindByAuthorPathIdMax)
    .describe('MongoDB ObjectId'),
  authorId: zod.string(),
});

export const postsControllerFindByAuthorQueryParams = zod.object({
  limit: zod
    .number()
    .optional()
    .describe('Number of items to return (1-100, default: 20)'),
  after: zod
    .string()
    .optional()
    .describe('Cursor token for next page (forward pagination)'),
  before: zod
    .string()
    .optional()
    .describe('Cursor token for previous page (backward pagination)'),
  sort: zod
    .enum([
      'title',
      'slug',
      'createdAt',
      'updatedAt',
      '-title',
      '-slug',
      '-createdAt',
      '-updatedAt',
    ])
    .optional()
    .describe(
      "Sort field with optional '-' prefix for descending. Allowed fields: title, slug, createdAt, updatedAt"
    ),
  projectId: zod.string().optional().describe('Filter by projectId'),
  domain: zod.string().optional().describe('Filter by domain (exact match)'),
  'domain.contains': zod
    .string()
    .optional()
    .describe('Filter where domain contains the value (case-sensitive)'),
  'domain.icontains': zod
    .string()
    .optional()
    .describe('Filter where domain contains the value (case-insensitive)'),
  'domain.startsWith': zod
    .string()
    .optional()
    .describe('Filter where domain starts with the value (case-sensitive)'),
  'domain.istartswith': zod
    .string()
    .optional()
    .describe('Filter where domain starts with the value (case-insensitive)'),
  title: zod.string().optional().describe('Filter by title (exact match)'),
  'title.contains': zod
    .string()
    .optional()
    .describe('Filter where title contains the value (case-sensitive)'),
  'title.icontains': zod
    .string()
    .optional()
    .describe('Filter where title contains the value (case-insensitive)'),
  'title.startsWith': zod
    .string()
    .optional()
    .describe('Filter where title starts with the value (case-sensitive)'),
  'title.istartswith': zod
    .string()
    .optional()
    .describe('Filter where title starts with the value (case-insensitive)'),
  slug: zod.string().optional().describe('Filter by slug (exact match)'),
  'slug.contains': zod
    .string()
    .optional()
    .describe('Filter where slug contains the value (case-sensitive)'),
  'slug.icontains': zod
    .string()
    .optional()
    .describe('Filter where slug contains the value (case-insensitive)'),
  'slug.startsWith': zod
    .string()
    .optional()
    .describe('Filter where slug starts with the value (case-sensitive)'),
  'slug.istartswith': zod
    .string()
    .optional()
    .describe('Filter where slug starts with the value (case-insensitive)'),
  description: zod
    .string()
    .optional()
    .describe('Filter by description (exact match)'),
  'description.contains': zod
    .string()
    .optional()
    .describe('Filter where description contains the value (case-sensitive)'),
  'description.icontains': zod
    .string()
    .optional()
    .describe('Filter where description contains the value (case-insensitive)'),
  'description.startsWith': zod
    .string()
    .optional()
    .describe(
      'Filter where description starts with the value (case-sensitive)'
    ),
  'description.istartswith': zod
    .string()
    .optional()
    .describe(
      'Filter where description starts with the value (case-insensitive)'
    ),
  tags: zod.string().optional().describe('Filter by tags (exact match)'),
  'tags.contains': zod
    .string()
    .optional()
    .describe('Filter where tags contains the value (case-sensitive)'),
  'tags.icontains': zod
    .string()
    .optional()
    .describe('Filter where tags contains the value (case-insensitive)'),
  'tags.startsWith': zod
    .string()
    .optional()
    .describe('Filter where tags starts with the value (case-sensitive)'),
  'tags.istartswith': zod
    .string()
    .optional()
    .describe('Filter where tags starts with the value (case-insensitive)'),
  type: zod.string().optional().describe('Filter by type (exact match)'),
  'type.contains': zod
    .string()
    .optional()
    .describe('Filter where type contains the value (case-sensitive)'),
  'type.icontains': zod
    .string()
    .optional()
    .describe('Filter where type contains the value (case-insensitive)'),
  'type.startsWith': zod
    .string()
    .optional()
    .describe('Filter where type starts with the value (case-sensitive)'),
  'type.istartswith': zod
    .string()
    .optional()
    .describe('Filter where type starts with the value (case-insensitive)'),
  status: zod.string().optional().describe('Filter by status (exact match)'),
  'status.contains': zod
    .string()
    .optional()
    .describe('Filter where status contains the value (case-sensitive)'),
  'status.icontains': zod
    .string()
    .optional()
    .describe('Filter where status contains the value (case-insensitive)'),
  'status.startsWith': zod
    .string()
    .optional()
    .describe('Filter where status starts with the value (case-sensitive)'),
  'status.istartswith': zod
    .string()
    .optional()
    .describe('Filter where status starts with the value (case-insensitive)'),
  authorId: zod.string().optional().describe('Filter by authorId'),
  categories: zod.string().optional().describe('Filter by categories'),
  createdAt: zod
    .string()
    .optional()
    .describe('Filter by createdAt (exact match, ISO date string for dates)'),
  'createdAt.gt': zod
    .string()
    .optional()
    .describe('Filter where createdAt is greater than'),
  'createdAt.gte': zod
    .string()
    .optional()
    .describe('Filter where createdAt is greater than or equal'),
  'createdAt.lt': zod
    .string()
    .optional()
    .describe('Filter where createdAt is less than'),
  'createdAt.lte': zod
    .string()
    .optional()
    .describe('Filter where createdAt is less than or equal'),
  updatedAt: zod
    .string()
    .optional()
    .describe('Filter by updatedAt (exact match, ISO date string for dates)'),
  'updatedAt.gt': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is greater than'),
  'updatedAt.gte': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is greater than or equal'),
  'updatedAt.lt': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is less than'),
  'updatedAt.lte': zod
    .string()
    .optional()
    .describe('Filter where updatedAt is less than or equal'),
});

export const postsControllerFindByAuthorResponseItemsItemProjectIdMin = 24;
export const postsControllerFindByAuthorResponseItemsItemProjectIdMax = 24;

export const postsControllerFindByAuthorResponseItemsItemDomainMax = 30;

export const postsControllerFindByAuthorResponseItemsItemTitleMin = 5;
export const postsControllerFindByAuthorResponseItemsItemTitleMax = 120;

export const postsControllerFindByAuthorResponseItemsItemSlugMin = 5;
export const postsControllerFindByAuthorResponseItemsItemSlugMax = 120;

export const postsControllerFindByAuthorResponseItemsItemDescriptionMin = 10;
export const postsControllerFindByAuthorResponseItemsItemDescriptionMax = 500;

export const postsControllerFindByAuthorResponseItemsItemIdMin = 24;
export const postsControllerFindByAuthorResponseItemsItemIdMax = 24;

export const postsControllerFindByAuthorResponseItemsItemAuthorIdMin = 24;
export const postsControllerFindByAuthorResponseItemsItemAuthorIdMax = 24;

export const postsControllerFindByAuthorResponseItemsItemFilesItemLocationTypeDefault =
  'Point';
export const postsControllerFindByAuthorResponseItemsItemFilesItemIdMin = 24;
export const postsControllerFindByAuthorResponseItemsItemFilesItemIdMax = 24;

export const postsControllerFindByAuthorResponseItemsItemAuthorIdMinOne = 24;
export const postsControllerFindByAuthorResponseItemsItemAuthorIdMaxOne = 24;

export const postsControllerFindByAuthorResponse = zod.object({
  items: zod
    .array(
      zod.object({
        createdAt: zod.string().datetime({}),
        updatedAt: zod.string().datetime({}),
        projectId: zod
          .string()
          .min(postsControllerFindByAuthorResponseItemsItemProjectIdMin)
          .max(postsControllerFindByAuthorResponseItemsItemProjectIdMax)
          .describe('The unique id'),
        domain: zod
          .string()
          .max(postsControllerFindByAuthorResponseItemsItemDomainMax)
          .describe(
            'Domain label for multi-site support (e.g., \"main-website\", \"blog-subsite\")'
          ),
        title: zod
          .string()
          .min(postsControllerFindByAuthorResponseItemsItemTitleMin)
          .max(postsControllerFindByAuthorResponseItemsItemTitleMax),
        slug: zod
          .string()
          .min(postsControllerFindByAuthorResponseItemsItemSlugMin)
          .max(postsControllerFindByAuthorResponseItemsItemSlugMax),
        description: zod
          .string()
          .min(postsControllerFindByAuthorResponseItemsItemDescriptionMin)
          .max(postsControllerFindByAuthorResponseItemsItemDescriptionMax)
          .optional(),
        content: zod.string().optional(),
        tags: zod.array(zod.string()).optional(),
        type: zod.enum(['category', 'post', 'article']).optional(),
        status: zod
          .enum([
            'draft',
            'hidden',
            'pending',
            'scheduled',
            'paused',
            'active',
            'completed',
            'published',
            'cancelled',
            'expired',
            'accepted',
            'rejected',
          ])
          .optional(),
        id: zod
          .string()
          .min(postsControllerFindByAuthorResponseItemsItemIdMin)
          .max(postsControllerFindByAuthorResponseItemsItemIdMax)
          .describe('The unique id'),
        authorId: zod
          .string()
          .min(postsControllerFindByAuthorResponseItemsItemAuthorIdMin)
          .max(postsControllerFindByAuthorResponseItemsItemAuthorIdMax)
          .describe('The unique id of the author'),
        files: zod
          .array(
            zod.object({
              altText: zod.string(),
              exif: zod
                .object({
                  Model: zod.string(),
                  Lens: zod.string(),
                  ISOSpeedRatings: zod.string(),
                  FocalLength: zod.string(),
                  FNumber: zod.string(),
                  ExposureTime: zod.string(),
                  WhiteBalance: zod.string(),
                  MeteringMode: zod.string(),
                  DateTime: zod.string(),
                  GPSLatitude: zod.string(),
                  GPSLongitude: zod.string(),
                })
                .optional(),
              location: zod
                .object({
                  type: zod.string(),
                  coordinates: zod.array(zod.number()),
                })
                .optional(),
              src: zod.string(),
              type: zod.string(),
              id: zod
                .string()
                .min(postsControllerFindByAuthorResponseItemsItemFilesItemIdMin)
                .max(postsControllerFindByAuthorResponseItemsItemFilesItemIdMax)
                .describe('The unique id'),
            })
          )
          .optional()
          .describe('Post files (origin field excluded)'),
        author: zod
          .object({
            id: zod
              .string()
              .min(postsControllerFindByAuthorResponseItemsItemAuthorIdMinOne)
              .max(postsControllerFindByAuthorResponseItemsItemAuthorIdMaxOne)
              .describe('The unique id of the author'),
            name: zod.string().describe('Author name'),
            username: zod
              .string()
              .optional()
              .describe(
                'Author username (falls back to userId if username not found)'
              ),
          })
          .optional()
          .describe('Post author information (populated)'),
        categories: zod
          .array(
            zod.object({
              id: zod.string().describe('The unique id'),
              slug: zod.string().describe('Category slug'),
              title: zod.string().describe('Category title'),
            })
          )
          .optional()
          .describe('Post categories (populated)'),
      })
    )
    .optional(),
  meta: zod
    .object({
      nextCursor: zod.string().optional(),
      prevCursor: zod.string().optional(),
      hasNextPage: zod.boolean(),
      hasPrevPage: zod.boolean(),
      limit: zod.number(),
      sort: zod.string(),
      order: zod.enum(['asc', 'desc']),
    })
    .optional(),
});
