/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import * as zod from 'zod';

/**
 * @summary Upload file to post
 */
export const postsFileControllerUploadFileParams = zod.object({
  post: zod.string(),
});

export const postsFileControllerUploadFileBody = zod.object({
  file: zod.instanceof(File).describe('The file to upload'),
  exif: zod.string().optional().describe('EXIF metadata as JSON string'),
});

export const postsFileControllerUploadFileResponse = zod.object({
  status: zod.boolean().describe('Response status as boolean'),
});

/**
 * @summary Update file metadata
 */
export const postsFileControllerUpdateFileParams = zod.object({
  post: zod.string(),
  id: zod.string(),
});

export const postsFileControllerUpdateFileBodyLocationTypeDefault = 'Point';

export const postsFileControllerUpdateFileBody = zod.object({
  altText: zod.string(),
  location: zod
    .object({
      type: zod.string(),
      coordinates: zod.array(zod.number()),
    })
    .optional(),
});

export const postsFileControllerUpdateFileResponse = zod.object({
  id: zod.string().describe('Response id as string'),
});

/**
 * @summary Delete file from post
 */
export const postsFileControllerDeleteFileParams = zod.object({
  post: zod.string(),
  id: zod.string(),
});

export const postsFileControllerDeleteFileResponse = zod.object({
  status: zod.boolean().describe('Response status as boolean'),
});
