/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  PostsFileControllerUploadFileBody,
  ResponseIdDto,
  ResponseStatusDto,
  UpdatePostFileDto
} from '../kodkafaApi.schemas';

import { clientMutator } from '../../../lib/api/client.mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Upload file to post
 */
export type postsFileControllerUploadFileResponse200 = {
  data: ResponseStatusDto
  status: 200
}

export type postsFileControllerUploadFileResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type postsFileControllerUploadFileResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type postsFileControllerUploadFileResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type postsFileControllerUploadFileResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type postsFileControllerUploadFileResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type postsFileControllerUploadFileResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type postsFileControllerUploadFileResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type postsFileControllerUploadFileResponseSuccess = (postsFileControllerUploadFileResponse200) & {
  headers: Headers;
};
export type postsFileControllerUploadFileResponseError = (postsFileControllerUploadFileResponse400 | postsFileControllerUploadFileResponse401 | postsFileControllerUploadFileResponse403 | postsFileControllerUploadFileResponse404 | postsFileControllerUploadFileResponse409 | postsFileControllerUploadFileResponse422 | postsFileControllerUploadFileResponse500) & {
  headers: Headers;
};

export type postsFileControllerUploadFileResponse = (postsFileControllerUploadFileResponseSuccess | postsFileControllerUploadFileResponseError)

export const getPostsFileControllerUploadFileUrl = (post: string,) => {


  

  return `/api/posts/${post}/files`
}

export const postsFileControllerUploadFile = async (post: string,
    postsFileControllerUploadFileBody: PostsFileControllerUploadFileBody, options?: RequestInit): Promise<postsFileControllerUploadFileResponse> => {
    const formData = new FormData();
formData.append(`file`, postsFileControllerUploadFileBody.file)
if(postsFileControllerUploadFileBody.exif !== undefined) {
 formData.append(`exif`, postsFileControllerUploadFileBody.exif)
 }

  return clientMutator<postsFileControllerUploadFileResponse>(getPostsFileControllerUploadFileUrl(post),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getPostsFileControllerUploadFileMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerUploadFile>>, TError,{post: string;data: PostsFileControllerUploadFileBody}, TContext>, request?: SecondParameter<typeof clientMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerUploadFile>>, TError,{post: string;data: PostsFileControllerUploadFileBody}, TContext> => {

const mutationKey = ['postsFileControllerUploadFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsFileControllerUploadFile>>, {post: string;data: PostsFileControllerUploadFileBody}> = (props) => {
          const {post,data} = props ?? {};

          return  postsFileControllerUploadFile(post,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostsFileControllerUploadFileMutationResult = NonNullable<Awaited<ReturnType<typeof postsFileControllerUploadFile>>>
    export type PostsFileControllerUploadFileMutationBody = PostsFileControllerUploadFileBody
    export type PostsFileControllerUploadFileMutationError = ErrorResponseDto

    /**
 * @summary Upload file to post
 */
export const usePostsFileControllerUploadFile = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerUploadFile>>, TError,{post: string;data: PostsFileControllerUploadFileBody}, TContext>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsFileControllerUploadFile>>,
        TError,
        {post: string;data: PostsFileControllerUploadFileBody},
        TContext
      > => {

      const mutationOptions = getPostsFileControllerUploadFileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update file metadata
 */
export type postsFileControllerUpdateFileResponse200 = {
  data: ResponseIdDto
  status: 200
}

export type postsFileControllerUpdateFileResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type postsFileControllerUpdateFileResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type postsFileControllerUpdateFileResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type postsFileControllerUpdateFileResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type postsFileControllerUpdateFileResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type postsFileControllerUpdateFileResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type postsFileControllerUpdateFileResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type postsFileControllerUpdateFileResponseSuccess = (postsFileControllerUpdateFileResponse200) & {
  headers: Headers;
};
export type postsFileControllerUpdateFileResponseError = (postsFileControllerUpdateFileResponse400 | postsFileControllerUpdateFileResponse401 | postsFileControllerUpdateFileResponse403 | postsFileControllerUpdateFileResponse404 | postsFileControllerUpdateFileResponse409 | postsFileControllerUpdateFileResponse422 | postsFileControllerUpdateFileResponse500) & {
  headers: Headers;
};

export type postsFileControllerUpdateFileResponse = (postsFileControllerUpdateFileResponseSuccess | postsFileControllerUpdateFileResponseError)

export const getPostsFileControllerUpdateFileUrl = (post: string,
    id: string,) => {


  

  return `/api/posts/${post}/files/${id}`
}

export const postsFileControllerUpdateFile = async (post: string,
    id: string,
    updatePostFileDto: UpdatePostFileDto, options?: RequestInit): Promise<postsFileControllerUpdateFileResponse> => {
  
  return clientMutator<postsFileControllerUpdateFileResponse>(getPostsFileControllerUpdateFileUrl(post,id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePostFileDto,)
  }
);}




export const getPostsFileControllerUpdateFileMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerUpdateFile>>, TError,{post: string;id: string;data: UpdatePostFileDto}, TContext>, request?: SecondParameter<typeof clientMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerUpdateFile>>, TError,{post: string;id: string;data: UpdatePostFileDto}, TContext> => {

const mutationKey = ['postsFileControllerUpdateFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsFileControllerUpdateFile>>, {post: string;id: string;data: UpdatePostFileDto}> = (props) => {
          const {post,id,data} = props ?? {};

          return  postsFileControllerUpdateFile(post,id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostsFileControllerUpdateFileMutationResult = NonNullable<Awaited<ReturnType<typeof postsFileControllerUpdateFile>>>
    export type PostsFileControllerUpdateFileMutationBody = UpdatePostFileDto
    export type PostsFileControllerUpdateFileMutationError = ErrorResponseDto

    /**
 * @summary Update file metadata
 */
export const usePostsFileControllerUpdateFile = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerUpdateFile>>, TError,{post: string;id: string;data: UpdatePostFileDto}, TContext>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsFileControllerUpdateFile>>,
        TError,
        {post: string;id: string;data: UpdatePostFileDto},
        TContext
      > => {

      const mutationOptions = getPostsFileControllerUpdateFileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete file from post
 */
export type postsFileControllerDeleteFileResponse200 = {
  data: ResponseStatusDto
  status: 200
}

export type postsFileControllerDeleteFileResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type postsFileControllerDeleteFileResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type postsFileControllerDeleteFileResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type postsFileControllerDeleteFileResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type postsFileControllerDeleteFileResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type postsFileControllerDeleteFileResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type postsFileControllerDeleteFileResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type postsFileControllerDeleteFileResponseSuccess = (postsFileControllerDeleteFileResponse200) & {
  headers: Headers;
};
export type postsFileControllerDeleteFileResponseError = (postsFileControllerDeleteFileResponse400 | postsFileControllerDeleteFileResponse401 | postsFileControllerDeleteFileResponse403 | postsFileControllerDeleteFileResponse404 | postsFileControllerDeleteFileResponse409 | postsFileControllerDeleteFileResponse422 | postsFileControllerDeleteFileResponse500) & {
  headers: Headers;
};

export type postsFileControllerDeleteFileResponse = (postsFileControllerDeleteFileResponseSuccess | postsFileControllerDeleteFileResponseError)

export const getPostsFileControllerDeleteFileUrl = (post: string,
    id: string,) => {


  

  return `/api/posts/${post}/files/${id}`
}

export const postsFileControllerDeleteFile = async (post: string,
    id: string, options?: RequestInit): Promise<postsFileControllerDeleteFileResponse> => {
  
  return clientMutator<postsFileControllerDeleteFileResponse>(getPostsFileControllerDeleteFileUrl(post,id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getPostsFileControllerDeleteFileMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerDeleteFile>>, TError,{post: string;id: string}, TContext>, request?: SecondParameter<typeof clientMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerDeleteFile>>, TError,{post: string;id: string}, TContext> => {

const mutationKey = ['postsFileControllerDeleteFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsFileControllerDeleteFile>>, {post: string;id: string}> = (props) => {
          const {post,id} = props ?? {};

          return  postsFileControllerDeleteFile(post,id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostsFileControllerDeleteFileMutationResult = NonNullable<Awaited<ReturnType<typeof postsFileControllerDeleteFile>>>
    
    export type PostsFileControllerDeleteFileMutationError = ErrorResponseDto

    /**
 * @summary Delete file from post
 */
export const usePostsFileControllerDeleteFile = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsFileControllerDeleteFile>>, TError,{post: string;id: string}, TContext>, request?: SecondParameter<typeof clientMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsFileControllerDeleteFile>>,
        TError,
        {post: string;id: string},
        TContext
      > => {

      const mutationOptions = getPostsFileControllerDeleteFileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    