/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * KODKAFA API
 * Stack: Nest.js + MongoDB + Mongoose + Redis - OAuth 2.1 Compliant
 * OpenAPI spec version: 0.0.3
 */
import type {
  AccountDto,
  AddAccountDto,
  ErrorResponseDto,
  OkDto,
  UsersAccountsControllerFindParams
} from '../../schemas';

import { ssrMutator } from '../../../lib/api/ssr.mutator';

/**
 * @summary  Add new account to user. 
 */
export type usersAccountsControllerAddResponse201 = {
  data: AccountDto
  status: 201
}

export type usersAccountsControllerAddResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type usersAccountsControllerAddResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type usersAccountsControllerAddResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type usersAccountsControllerAddResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type usersAccountsControllerAddResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type usersAccountsControllerAddResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type usersAccountsControllerAddResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type usersAccountsControllerAddResponseSuccess = (usersAccountsControllerAddResponse201) & {
  headers: Headers;
};
export type usersAccountsControllerAddResponseError = (usersAccountsControllerAddResponse400 | usersAccountsControllerAddResponse401 | usersAccountsControllerAddResponse403 | usersAccountsControllerAddResponse404 | usersAccountsControllerAddResponse409 | usersAccountsControllerAddResponse422 | usersAccountsControllerAddResponse500) & {
  headers: Headers;
};

export type usersAccountsControllerAddResponse = (usersAccountsControllerAddResponseSuccess | usersAccountsControllerAddResponseError)

export const getUsersAccountsControllerAddUrl = () => {


  

  return `/api/users/accounts`
}

export const usersAccountsControllerAdd = async (addAccountDto: AddAccountDto, options?: RequestInit): Promise<usersAccountsControllerAddResponse> => {
  
  return ssrMutator<usersAccountsControllerAddResponse>(getUsersAccountsControllerAddUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addAccountDto,)
  }
);}


/**
 * @summary  Find specific accounts by user id. 
 */
export type usersAccountsControllerFindResponse200 = {
  data: AccountDto[]
  status: 200
}

export type usersAccountsControllerFindResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type usersAccountsControllerFindResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type usersAccountsControllerFindResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type usersAccountsControllerFindResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type usersAccountsControllerFindResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type usersAccountsControllerFindResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type usersAccountsControllerFindResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type usersAccountsControllerFindResponseSuccess = (usersAccountsControllerFindResponse200) & {
  headers: Headers;
};
export type usersAccountsControllerFindResponseError = (usersAccountsControllerFindResponse400 | usersAccountsControllerFindResponse401 | usersAccountsControllerFindResponse403 | usersAccountsControllerFindResponse404 | usersAccountsControllerFindResponse409 | usersAccountsControllerFindResponse422 | usersAccountsControllerFindResponse500) & {
  headers: Headers;
};

export type usersAccountsControllerFindResponse = (usersAccountsControllerFindResponseSuccess | usersAccountsControllerFindResponseError)

export const getUsersAccountsControllerFindUrl = (params: UsersAccountsControllerFindParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/users/accounts?${stringifiedParams}` : `/api/users/accounts`
}

export const usersAccountsControllerFind = async (params: UsersAccountsControllerFindParams, options?: RequestInit): Promise<usersAccountsControllerFindResponse> => {
  
  return ssrMutator<usersAccountsControllerFindResponse>(getUsersAccountsControllerFindUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Update an account by user id.
 */
export type usersAccountsControllerUpdateResponse200 = {
  data: OkDto
  status: 200
}

export type usersAccountsControllerUpdateResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type usersAccountsControllerUpdateResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type usersAccountsControllerUpdateResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type usersAccountsControllerUpdateResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type usersAccountsControllerUpdateResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type usersAccountsControllerUpdateResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type usersAccountsControllerUpdateResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type usersAccountsControllerUpdateResponseSuccess = (usersAccountsControllerUpdateResponse200) & {
  headers: Headers;
};
export type usersAccountsControllerUpdateResponseError = (usersAccountsControllerUpdateResponse400 | usersAccountsControllerUpdateResponse401 | usersAccountsControllerUpdateResponse403 | usersAccountsControllerUpdateResponse404 | usersAccountsControllerUpdateResponse409 | usersAccountsControllerUpdateResponse422 | usersAccountsControllerUpdateResponse500) & {
  headers: Headers;
};

export type usersAccountsControllerUpdateResponse = (usersAccountsControllerUpdateResponseSuccess | usersAccountsControllerUpdateResponseError)

export const getUsersAccountsControllerUpdateUrl = () => {


  

  return `/api/users/accounts`
}

export const usersAccountsControllerUpdate = async (accountDto: AccountDto, options?: RequestInit): Promise<usersAccountsControllerUpdateResponse> => {
  
  return ssrMutator<usersAccountsControllerUpdateResponse>(getUsersAccountsControllerUpdateUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      accountDto,)
  }
);}


/**
 * @summary Remove specific account by user id. 
 */
export type usersAccountsControllerRemoveResponse200 = {
  data: OkDto
  status: 200
}

export type usersAccountsControllerRemoveResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type usersAccountsControllerRemoveResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type usersAccountsControllerRemoveResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type usersAccountsControllerRemoveResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type usersAccountsControllerRemoveResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type usersAccountsControllerRemoveResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type usersAccountsControllerRemoveResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type usersAccountsControllerRemoveResponseSuccess = (usersAccountsControllerRemoveResponse200) & {
  headers: Headers;
};
export type usersAccountsControllerRemoveResponseError = (usersAccountsControllerRemoveResponse400 | usersAccountsControllerRemoveResponse401 | usersAccountsControllerRemoveResponse403 | usersAccountsControllerRemoveResponse404 | usersAccountsControllerRemoveResponse409 | usersAccountsControllerRemoveResponse422 | usersAccountsControllerRemoveResponse500) & {
  headers: Headers;
};

export type usersAccountsControllerRemoveResponse = (usersAccountsControllerRemoveResponseSuccess | usersAccountsControllerRemoveResponseError)

export const getUsersAccountsControllerRemoveUrl = () => {


  

  return `/api/users/accounts`
}

export const usersAccountsControllerRemove = async (accountDto: AccountDto, options?: RequestInit): Promise<usersAccountsControllerRemoveResponse> => {
  
  return ssrMutator<usersAccountsControllerRemoveResponse>(getUsersAccountsControllerRemoveUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      accountDto,)
  }
);}


/**
 * @summary Set as primary. 
 */
export type usersAccountsControllerSetPrimaryResponse200 = {
  data: AccountDto[]
  status: 200
}

export type usersAccountsControllerSetPrimaryResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type usersAccountsControllerSetPrimaryResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type usersAccountsControllerSetPrimaryResponse403 = {
  data: ErrorResponseDto
  status: 403
}

export type usersAccountsControllerSetPrimaryResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type usersAccountsControllerSetPrimaryResponse409 = {
  data: ErrorResponseDto
  status: 409
}

export type usersAccountsControllerSetPrimaryResponse422 = {
  data: ErrorResponseDto
  status: 422
}

export type usersAccountsControllerSetPrimaryResponse500 = {
  data: ErrorResponseDto
  status: 500
}
    
export type usersAccountsControllerSetPrimaryResponseSuccess = (usersAccountsControllerSetPrimaryResponse200) & {
  headers: Headers;
};
export type usersAccountsControllerSetPrimaryResponseError = (usersAccountsControllerSetPrimaryResponse400 | usersAccountsControllerSetPrimaryResponse401 | usersAccountsControllerSetPrimaryResponse403 | usersAccountsControllerSetPrimaryResponse404 | usersAccountsControllerSetPrimaryResponse409 | usersAccountsControllerSetPrimaryResponse422 | usersAccountsControllerSetPrimaryResponse500) & {
  headers: Headers;
};

export type usersAccountsControllerSetPrimaryResponse = (usersAccountsControllerSetPrimaryResponseSuccess | usersAccountsControllerSetPrimaryResponseError)

export const getUsersAccountsControllerSetPrimaryUrl = () => {


  

  return `/api/users/accounts/set-primary`
}

export const usersAccountsControllerSetPrimary = async (accountDto: AccountDto, options?: RequestInit): Promise<usersAccountsControllerSetPrimaryResponse> => {
  
  return ssrMutator<usersAccountsControllerSetPrimaryResponse>(getUsersAccountsControllerSetPrimaryUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      accountDto,)
  }
);}


